### ISSUE TITLE
WindowConverter creates an array with null entries because of '<s>' word.

### ISSUE THREAD

**Issue by jaloncad** [eclipse/deeplearning4j#2132]
Hi all,

I'm working with ParagraphVectors, but I have a NullPointerException because windows has `<s>` words and not in my wordVectorMatrix `data[i] = vec.getWordVectorMatrix(window.getWord(i));`:

```
java.lang.NullPointerException
    at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.concat(CpuNDArrayFactory.java:578)
    at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4795)
    at org.nd4j.linalg.factory.BaseNDArrayFactory.hstack(BaseNDArrayFactory.java:1190)
    at org.nd4j.linalg.factory.Nd4j.hstack(Nd4j.java:4658)
    at org.deeplearning4j.text.movingwindow.WindowConverter.asExampleMatrix(WindowConverter.java:100)
    at org.deeplearning4j.models.word2vec.iterator.Word2VecDataSetIterator.fromCached(Word2VecDataSetIterator.java:186)
    at org.deeplearning4j.models.word2vec.iterator.Word2VecDataSetIterator.next(Word2VecDataSetIterator.java:152)
    at org.deeplearning4j.models.word2vec.iterator.Word2VecDataSetIterator.next(Word2VecDataSetIterator.java:275)
    at org.deeplearning4j.models.word2vec.iterator.Word2VecDataSetIterator.next(Word2VecDataSetIterator.java:46)
```

![windowconverter_java](https://cloud.githubusercontent.com/assets/87710/18816887/06f10a12-8353-11e6-9ea0-03297af8e6f4.jpg)
![cpundarrayfactory_class](https://cloud.githubusercontent.com/assets/87710/18816888/06f535b0-8353-11e6-8405-b34307e79fe8.jpg)

Juan.

**Comment by agibsonccc** [comment]
Closing old issues.
