### ISSUE TITLE
Spark Glove: NullPointerException 

### ISSUE THREAD

**Issue by gerdhub** [eclipse/deeplearning4j#2243]
This is a follow-up to #948:

```
Exception in thread "main" java.lang.NullPointerException
    at org.deeplearning4j.spark.text.functions.TextPipeline.setRDDVarMap(TextPipeline.java:88)
    at org.deeplearning4j.spark.text.functions.TextPipeline.<init>(TextPipeline.java:74)
    at org.deeplearning4j.spark.models.embeddings.glove.Glove.train(Glove.java:145)
```

This is because in org.deeplearning4j.spark.models.embeddings.glove.Glove.train not all Variables are set:

```
 Map<String, Object> tokenizerVarMap = new HashMap<String, Object>() {{
            put("numWords", numWords);
            put("nGrams", nGrams);
            put("tokenizer", tokenizer);
            put("tokenPreprocessor", tokenPreprocessor);
            put("removeStop", removeStop);
        }};
```

But these Variables are requested:

```
this.corpusRDD = corpusRDD;
        this.numWords = (int) tokenizerVarMap.get("numWords");
        // TokenizerFunction Settings
        this.nGrams = (int) tokenizerVarMap.get("nGrams");
        this.tokenizer = (String) tokenizerVarMap.get("tokenizer");
        this.tokenizerPreprocessor = (String) tokenizerVarMap.get("tokenPreprocessor");
        this.useUnk = (boolean) tokenizerVarMap.get("useUnk");
        this.configuration = (VectorsConfiguration) tokenizerVarMap.get("vectorsConfiguration");
        // Remove Stop words
       // if ((boolean) tokenizerVarMap.get("removeStop")) {
            stopWords = (List<String>) tokenizerVarMap.get("stopWords");
    //    }
```

Please fix this.

**Comment by huitseeker** [comment]
Thanks for your report! It would be tremendously useful to have news about which versions of underlying software you are using. Would you mind confirming:
- project / package version (or branch if you are building off the repo),
- java version,
- CUDA version (if applicable),
- BLAS version (if applicable)
Thanks for your help !

**Comment by raver119** [comment]
No need. We know about the problem with Glove on spark. It wasn't ever working as far as i know. Hopefully in next release will cover it again.
