### ISSUE TITLE
 LineSentenceiterator: Resetting to invalid mark 

### ISSUE THREAD

**Issue by carschno** [eclipse/deeplearning4j#33]
As already [posted on the mailing list](https://groups.google.com/forum/#!topic/deeplearning4j/5VZgN8bWBnc), when training a Word2Vec model fed from a LineSentenceIterator, the following exception is thrown:

```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Resetting to invalid mark
    at org.deeplearning4j.word2vec.sentenceiterator.LineSentenceIterator.reset(LineSentenceIterator.java:64)
    at org.deeplearning4j.word2vec.Word2Vec.train(Word2Vec.java:395)
    ... 2 more
Caused by: java.io.IOException: Resetting to invalid mark
    at java.io.BufferedInputStream.reset(BufferedInputStream.java:437)
    at org.deeplearning4j.word2vec.sentenceiterator.LineSentenceIterator.reset(LineSentenceIterator.java:61)
    ... 3 more
```

I did some basic debugging and figured that this happens because the `InputReader`'s `markpos` field is set to -1 when `reset()` is called. However, I haven't been able to fix it because I don't really understand why `reset()` is called in the first place.

**Comment by mikaelhg** [comment]
@agibsonccc Which release was this removed for? Because I'm hitting this on release 0.9.1, when instantiating a `BasicLineIterator` with an `InputStream` instance.

**Comment by agibsonccc** [comment]
@mikaelhg could you please not post on 3 year old issues? I'm locking this. File an appropriate issue with some code to reproduce this please.
