### ISSUE TITLE
ParallelWrapper throws ClosedByInterruptException

### ISSUE THREAD

**Issue by shengc** [eclipse/deeplearning4j#3990]
I am using latest release version 0.9.1, and running on CPU back end.

relevant code:
```scala
 val pw = new ParallelWrapper.Builder(nn).workers(2).prefetchBuffer(2).build()
 pw.fit(ds(trainDataPath))
```

stack trace:
```scala
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: java.nio.channels.ClosedByInterruptException
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: edu.stanford.nlp.io.RuntimeIOException: java.nio.channels.ClosedByInterruptException
    at edu.stanford.nlp.process.PTBTokenizer.getNext(PTBTokenizer.java:294)
    at edu.stanford.nlp.process.PTBTokenizer.getNext(PTBTokenizer.java:176)
    at edu.stanford.nlp.process.AbstractTokenizer.hasNext(AbstractTokenizer.java:60)
    at edu.stanford.nlp.process.AbstractTokenizer.tokenize(AbstractTokenizer.java:99)
    at experiment.ExperimentProducer$.produce(ExperimentProducer.scala:90)
    at experiment.ExperimentFileCallback$class.call(ExperimentFileCallback.scala:19)
experiment 2017-08-31 12:26:19,584 [] INFO  [main] o.d.p.ParallelWrapper          - Starting ParallelWrapper training round...
    at org.deeplearning4j.datasets.iterator.FileSplitDataSetIterator.next(FileSplitDataSetIterator.java:109)
    at org.deeplearning4j.datasets.iterator.FileSplitDataSetIterator.next(FileSplitDataSetIterator.java:20)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:417)
Caused by: java.nio.channels.ClosedByInterruptException
    at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:164)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.read1(BufferedReader.java:210)
    at java.io.BufferedReader.read(BufferedReader.java:286)
    at edu.stanford.nlp.process.PTBLexer.zzRefill(PTBLexer.java)
    at edu.stanford.nlp.process.PTBLexer.next(PTBLexer.java)
    at edu.stanford.nlp.process.PTBTokenizer.getNext(PTBTokenizer.java:292
```

**Comment by raver119** [comment]
Can you get me some code that reproduces this exception?

**Comment by shengc** [comment]
@raver119 

Using a `FileSplitDataSetItertor` instead of `FileSplitParallelDataSetIterator` makes the error go away. Is it somehow related to https://github.com/deeplearning4j/deeplearning4j/issues/3281 that `AsyncDataSetIterator` should not be used when in `SEPARATE WorkspaceMode` ?

**Comment by shengc** [comment]
Ok, another problem for `ParallelWrapper`....

The following one throws `UnsupportOperationException` on `AbstractList`, which comes from `nn.addListeners(new StatsListener(st))`
```scala
    nn.setListeners(new ScoreIterationListener(numIterations / 10))
    import org.deeplearning4j.parallelism.ParallelWrapper
    val pw= new ParallelWrapper.Builder(nn).workers(2).prefetchBuffer(2).build()
    ui foreach { server =>
      val st = new InMemoryStatsStorage()
      server.attach(st)
      nn.addListeners(new StatsListener(st))
    }
    pw.fit(ds(trainDataPath)
```

However by moving the line that instantiates ParallelWrapper after the call to `nn.addListeners(...)`, the error disappears,
```scala
    nn.setListeners(new ScoreIterationListener(numIterations / 10))
    ui foreach { server =>
      val st = new InMemoryStatsStorage()
      server.attach(st)
      nn.addListeners(new StatsListener(st))
    }
    import org.deeplearning4j.parallelism.ParallelWrapper
    val pw= new ParallelWrapper.Builder(nn).workers(2).prefetchBuffer(2).build()
    pw.fit(ds(trainDataPath))
```
