### ISSUE TITLE
Errors in running GloveExample in DL4J-examples

### ISSUE THREAD

**Issue by lingvisa** [eclipse/deeplearning4j#4212]
I didn't change anything and just run the default example, but received this error message. What might be the problem?

```
1.1.7.jar" org.deeplearning4j.examples.nlp.glove.GloVeExample
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.d.m.s.SequenceVectors - Starting vocabulary building...
o.d.m.w.w.VocabConstructor - Sequences checked: [71], Current vocabulary size: [28]; Sequences/sec: [33.05];
o.d.m.e.l.WordVectorSerializer - Projected memory use for model: [0.02 MB]
o.d.m.e.i.InMemoryLookupTable - Initializing syn1...
o.d.m.s.SequenceVectors - Building learning algorithms:
o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [GloVe]
o.d.m.e.l.i.e.GloVe - GloVe params: {Max Memory: [0], Learning rate: [0.1], Alpha: [0.75], xMax: [100.0], Symmetric: [true], Shuffle: [true]}
o.d.m.g.AbstractCoOccurrences - Actual memory limit: [3780640768]
o.d.m.g.AbstractCoOccurrences - Number of word pairs saved so far: [454]
o.d.m.g.AbstractCoOccurrences - CoOccurrences map was built.
o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "GloVe ELA t.2" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [421] pairs, Error was [8.77615388324181]
Exception in thread "GloVe ELA t.2" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [736] pairs, Error was [6.50891944035564]
o.d.m.e.l.i.e.GloVe - Processed [1190] pairs, Error was [8.694534749871718]
o.d.m.e.l.i.e.GloVe - Processed [1644] pairs, Error was [8.390842903821625]
o.d.m.e.l.i.e.GloVe - Processed [2098] pairs, Error was [8.126683610228756]
o.d.m.e.l.i.e.GloVe - Processed [2552] pairs, Error was [7.8741337047486075]
o.d.m.e.l.i.e.GloVe - Processed [3006] pairs, Error was [7.638759851907549]
o.d.m.e.l.i.e.GloVe - Processed [3460] pairs, Error was [7.421269145066776]
o.d.m.e.l.i.e.GloVe - Processed [3914] pairs, Error was [7.219817799753098]
Exception in thread "GloVe ELA t.0" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [4358] pairs, Error was [6.340276097827357]
o.d.m.e.l.i.e.GloVe - Processed [4812] pairs, Error was [6.880693995054875]
o.d.m.e.l.i.e.GloVe - Processed [5266] pairs, Error was [6.717555712048161]
o.d.m.e.l.i.e.GloVe - Processed [5720] pairs, Error was [6.566312666567867]
Exception in thread "GloVe ELA t.0" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [6126] pairs, Error was [5.739417753865672]
o.d.m.e.l.i.e.GloVe - Processed [6580] pairs, Error was [6.308963946293283]
o.d.m.e.l.i.e.GloVe - Processed [7034] pairs, Error was [6.187631401991596]
Exception in thread "GloVe ELA t.2" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [7381] pairs, Error was [4.856713125768342]
Exception in thread "GloVe ELA t.0" java.lang.NullPointerException
o.d.m.e.l.i.e.GloVe - Processed [7763] pairs, Error was [5.236226830378817]
o.d.m.e.l.i.e.GloVe - Processed [8217] pairs, Error was [5.898072603096695]
Exception in thread "GloVe ELA t.3" java.lang.NullPointerException
o.d.m.e.l.i.e.GloVe - Processed [8344] pairs, Error was [1.6073951146509666]
Exception in thread "GloVe ELA t.0" java.lang.NullPointerException
o.d.m.e.l.i.e.GloVe - Processed [8744] pairs, Error was [5.038342630863234]
o.d.m.e.l.i.e.GloVe - Processed [9198] pairs, Error was [5.711398310246838]
o.d.m.e.l.i.e.GloVe - Processed [9652] pairs, Error was [5.630855539552693]
Exception in thread "GloVe ELA t.1" java.lang.NullPointerException
o.d.m.e.l.i.e.GloVe - Processed [10039] pairs, Error was [4.710978363096721]
Exception in thread "GloVe ELA t.3" java.lang.NullPointerException
o.d.m.e.l.i.e.GloVe - Processed [10421] pairs, Error was [4.606325618589391]
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.s.SequenceVectors - Time spent on training: 22367 ms
o.d.e.n.g.GloVeExample - Day/night similarity: NaN
o.d.e.n.g.GloVeExample - Nearest words to 'day': []

Process finished with exit code 0

```

**Comment by pirocks** [comment]
I've found that reducing the learning rate to about 0.01 can get rid of the NaNs but not the NullPointerExceptions.

**Comment by treo** [comment]
Closing due to GloVe feature removal. See https://github.com/eclipse/deeplearning4j/issues/7855#issuecomment-624616313
