### ISSUE TITLE
Dependency conflicts with deeplearning4j-parallel-wrapper_2.11 and Zeppelin

### ISSUE THREAD

**Issue by crockpotveggies** [eclipse/deeplearning4j#4216]
#### Issue Description

Currently if I import the ParallelWrapper artifact from Maven into Zeppelin, my SparkInterpreter begins to fail and emit classloader related issues.

```
java.lang.VerifyError: Cannot inherit from final class
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```
and

```
...java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
  at org.apache.spark.SparkContext.withScope(SparkContext.scala:701)
  at org.apache.spark.SparkContext.textFile(SparkContext.scala:819)
  ... 82 elided
```
If I completely remove the artifact and restart the interpreter, it functions as expected.

#### Version Information

* Deeplearning4j 0.9.1
* Zeppelin 0.7.3
* CUDA 8.0, 9.0

**Comment by raver119** [comment]
Is this issue still relevant?
