### ISSUE TITLE
GloVe example NaN Error

### ISSUE THREAD

**Issue by ghazalehnt** [eclipse/deeplearning4j#4257]
There was an issue in earlier versions but was fixed in 0.8.0 version [https://github.com/deeplearning4j/deeplearning4j/issues/1622](https://github.com/deeplearning4j/deeplearning4j/issues/1622)
Here is the output I got from GloVe example after importing dl4j-examples and version is 0.9.1
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [32]; Memory: [26.7GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.d.m.s.SequenceVectors - Starting vocabulary building...
o.d.m.w.w.VocabConstructor - Sequences checked: [97162], Current vocabulary size: [242]; Sequences/sec: [29487.71];
o.d.m.e.l.WordVectorSerializer - Projected memory use for model: [0.18 MB]
o.d.m.e.i.InMemoryLookupTable - Initializing syn1...
o.d.m.s.SequenceVectors - Building learning algorithms:
o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [GloVe]
o.d.m.e.l.i.e.GloVe - GloVe params: {Max Memory: [1], Learning rate: [0.1], Alpha: [0.75], xMax: [100.0], Symmetric: [true], Shuffle: [true]}
o.d.m.g.AbstractCoOccurrences - Actual memory limit: [1073741824]
o.d.m.g.AbstractCoOccurrences - Number of word pairs saved so far: [47194]
o.d.m.g.AbstractCoOccurrences - CoOccurrences map was built.
o.d.m.s.SequenceVectors - Starting learning process...
o.d.m.e.l.i.e.GloVe - Processed [47194] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [94388] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [141582] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [188776] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [235970] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [283164] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [330358] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [377552] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [424746] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [471940] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [519134] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [566328] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [613522] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [660716] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [707910] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [755104] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [802298] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [849492] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [896686] pairs, Error was [NaN]
Exception in thread "GloVe ELA t.9" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [943742] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [990936] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [1000003] word pairs so far...
o.d.m.e.l.i.e.GloVe - Processed [1038130] pairs, Error was [NaN]
Exception in thread "GloVe ELA t.30" java.lang.NullPointerException
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:160)
	at org.deeplearning4j.models.glove.AbstractCoOccurrences$1.next(AbstractCoOccurrences.java:147)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe$GloveCalculationsThread.run(GloVe.java:262)
o.d.m.e.l.i.e.GloVe - Processed [1084785] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [1131979] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - Processed [1179173] pairs, Error was [NaN]
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.e.l.i.e.GloVe - GloVe finalizer...
o.d.m.s.SequenceVectors - Time spent on training: 70729 ms
o.d.e.n.g.GloVeExample - Day/night similarity: NaN
o.d.e.n.g.GloVeExample - Nearest words to 'day': [i, do, to, nt, the, that, s, he, you, is]
```
I'm new to dl4j and just started with it so, It would be very helpful if someone could say if I have some wrong configs or there is a bug. Thanks

**Comment by raver119** [comment]
I think that's a bug. I'll take a look there once i have some free time.

**Comment by treo** [comment]
Closing due to GloVe feature removal. See https://github.com/eclipse/deeplearning4j/issues/7855#issuecomment-624616313
