### ISSUE TITLE
Arbiter: MultiLayerSpace only supports identical auto-gen'd layerspaces

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5177]
> There is a parameter for the MultiLayerSpace (duplicateConfig) which allows the possibility of creating variable numbers of auto-generated layers, with different hyperparameters for each layer. Unfo, this is not yet implemented, which reduces the value of the Arbiter in exploring different NN architectures. Could it be added please?

> This is the error, which I have checked in the github source code. My code is working fine using the Arbiter with identical layers (i.e. the duplicateConfig parameter is true)

> Exception in thread "main" java.lang.UnsupportedOperationException: Not yet implemented
at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:71)
at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:24)

Migrated from: https://github.com/deeplearning4j/Arbiter/issues/80

**Comment by AlexDBlack** [comment]
See also: https://github.com/deeplearning4j/Arbiter/issues/53
