### ISSUE TITLE
Jumpy: ModuleNotFoundError: No module named 'ops'

### ISSUE THREAD

**Issue by akshaysharma096** [eclipse/deeplearning4j#5283]
Calling operations **ops**, causes `ModuleNotFoundError: No module named 'ops'`

**Comment by akshaysharma096** [comment]
`Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jumpy as jp
>>> x = jp.zeros((32, 16))
>>> y = jp.ones((32, 16))
>>> x.shape()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object is not callable
>>> x.shape
(32, 16)
>>> x.transpose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akshaysharma/Documents/deeplearning4j/jumpy/ndarray.py", line 403, in __getattr__
    import ops
ModuleNotFoundError: No module named 'ops'
>>> x.transpose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akshaysharma/Documents/deeplearning4j/jumpy/ndarray.py", line 403, in __getattr__
    import ops
ModuleNotFoundError: No module named 'ops'
`

**Comment by akshaysharma096** [comment]
Once https://github.com/deeplearning4j/deeplearning4j/pull/5282, is merged, I will raise the PR for this issue, as well.
