### ISSUE TITLE
DL4J: JSON deserialization issue with bidirectional wrapper layer

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#5289]
It looks like the JSON backward compatibility code for the JSON format change between 1.0.0-alpha and 1.0.0-beta isn't functioning correctly for bidirectional layers...

```
Exception in thread "main" java.lang.RuntimeException: Error deserializing ComputationGraphConfiguration - configuration may have a custom layer, vertex or preprocessor, in pre version 1.0.0-alpha JSON format. These layers can be deserialized by first registering them with NeuralNetConfiguration.registerLegacyCustomClassesForJSON(Class...)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.fromJson(ComputationGraphConfiguration.java:169)
	at io.skymind.orange.Temp.main(Temp.java:18)
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Cannot deserialize legacy JSON format of object with name "LayerVertex" of type org.deeplearning4j.nn.conf.graph.GraphVertex (through reference chain: org.deeplearning4j.nn.conf.ComputationGraphConfiguration["vertices"]->java.util.LinkedHashMap["lstm-0"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at org.nd4j.shade.jackson.databind.deser.std.ContainerDeserializerBase.wrapAndThrow(ContainerDeserializerBase.java:88)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:485)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.deeplearning4j.nn.conf.serde.ComputationGraphConfigurationDeserializer.deserialize(ComputationGraphConfigurationDeserializer.java:36)
	at org.deeplearning4j.nn.conf.serde.ComputationGraphConfigurationDeserializer.deserialize(ComputationGraphConfigurationDeserializer.java:26)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.fromJson(ComputationGraphConfiguration.java:164)
	... 1 more
Caused by: java.lang.IllegalStateException: Cannot deserialize legacy JSON format of object with name "LayerVertex" of type org.deeplearning4j.nn.conf.graph.GraphVertex
	at org.nd4j.serde.json.BaseLegacyDeserializer.deserialize(BaseLegacyDeserializer.java:88)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:140)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:103)
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:475)
	... 13 more
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Cannot deserialize legacy JSON format of object with name "Bidirectional" of type org.deeplearning4j.nn.conf.layers.Layer (through reference chain: org.deeplearning4j.nn.conf.graph.LayerVertex["layerConf"]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.wrapAndThrow(BeanPropertyMap.java:439)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap._findDeserializeAndSet2(BeanPropertyMap.java:315)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:291)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.nd4j.serde.json.BaseLegacyDeserializer.deserialize(BaseLegacyDeserializer.java:84)
	... 17 more
Caused by: java.lang.IllegalStateException: Cannot deserialize legacy JSON format of object with name "Bidirectional" of type org.deeplearning4j.nn.conf.layers.Layer
	at org.nd4j.serde.json.BaseLegacyDeserializer.deserialize(BaseLegacyDeserializer.java:88)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:140)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:103)
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap._findDeserializeAndSet2(BeanPropertyMap.java:313)
	... 28 more
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Can not construct instance of org.deeplearning4j.nn.conf.layers.Layer, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: {"bwd":{"LSTM":{"activationFn":{"TanH":{}},"biasInit":0.0,"biasUpdater":null,"constraints":null,"dist":null,"distRecurrent":null,"forgetGateBiasInit":1.0,"gateActivationFn":{"Sigmoid":{}},"gradientNormalization":"None","gradientNormalizationThreshold":1.0,"idropout":null,"iupdater":{"@class":"org.nd4j.linalg.learning.config.Adam","beta1":0.9,"beta2":0.999,"epsilon":1.0E-8,"learningRate":0.001},"l1":0.0,"l1Bias":0.0,"l2":1.0E-5,"l2Bias":0.0,"layerName":"lstm-0","nin":23,"nout":56,"weightInit":"XAVIER","weightInitRecurrent":null,"weightNoise":null}},"constraints":null,"fwd":{"LSTM":{"activationFn":{"TanH":{}},"biasInit":0.0,"biasUpdater":null,"constraints":null,"dist":null,"distRecurrent":null,"forgetGateBiasInit":1.0,"gateActivationFn":{"Sigmoid":{}},"gradientNormalization":"None","gradientNormalizationThreshold":1.0,"idropout":null,"iupdater":{"@class":"org.nd4j.linalg.learning.config.Adam","beta1":0.9,"beta2":0.999,"epsilon":1.0E-8,"learningRate":0.001},"l1":0.0,"l1Bias":0.0,"l2":1.0E-5,"l2Bias":0.0,"layerName":"lstm-0","nin":23,"nout":56,"weightInit":"XAVIER","weightInitRecurrent":null,"weightNoise":null}},"idropout":null,"layerName":"lstm-0","mode":"CONCAT"}; line: 1, column: 2] (through reference chain: org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional["bwd"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at org.nd4j.shade.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:857)
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.nd4j.serde.json.BaseLegacyDeserializer.deserialize(BaseLegacyDeserializer.java:84)
```

Aha! Link: https://skymindai.aha.io/features/DL4J-104

**Comment by AlexDBlack** [comment]
Obsolete
