### ISSUE TITLE
Keras import examples broken in 1.0.0-beta2

### ISSUE THREAD

**Issue by ibnopcit** [eclipse/deeplearning4j#6385]
Running the org.deeplearning4j.examples.modelimport.keras.basic.SimpleSequentialMlpImport or SimpleFunctionalMlpImport gives the following error:

```
====== org.deeplearning4j.examples.modelimport.keras.basic.SimpleSequentialMlpImport

o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [3.6GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
{class_name=SGD, config={nesterov=false, lr=0.009999999776482582, momentum=0.0, decay=0.0}}
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasOptimizerUtils.mapOptimizer(KerasOptimizerUtils.java:119)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.importTrainingConfiguration(KerasModel.java:253)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:132)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:61)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:180)
	at org.deeplearning4j.examples.modelimport.keras.basic.SimpleSequentialMlpImport.main(SimpleSequentialMlpImport.java:70)
```

Seen on Mac and CentOS 6.

A basic Keras load as described in the quickstart documentation also gives this error, but works in 1.0.0-beta.

**Comment by maxpumperla** [comment]
@ibnopcit yes, that's a little unfortunate. It works on master (and SNAPSHOTS),  but I'll have to modify that example. if I remember correctly it can't read `momentum`, although it's there. anyway, will fix it soon. thanks!

**Comment by maxpumperla** [comment]
@u-ryo thanks, good catch.

**Comment by andreped** [comment]
Has this been fixed yet?
I used DL4J 1.0.0-beta4, and got the same error using SGD as optimizer...

**Comment by AlexDBlack** [comment]
Looks like maybe it has not :/
https://github.com/keras-team/keras/blob/master/keras/optimizers.py#L177
https://github.com/eclipse/deeplearning4j/blob/b5f0ec072f3fd0da566e32f82c0e43ca36553f39/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasOptimizerUtils.java#L120

@andreped That said, given the try/catch, it's probably not causing the exception you are running into.
Can you post the exact stack trace so we can make sure it's the same issue?

**Comment by AlexDBlack** [comment]
Fixed here, will be merged back to eclipse/deeplearning4j master soonish: https://github.com/SkymindIO/deeplearning4j/pull/81
