### ISSUE TITLE
Cast exception importing Keras model (1.0.0-beta2)

### ISSUE THREAD

**Issue by ibnopcit** [eclipse/deeplearning4j#6386]
I'm attempting to import [this Keras model](https://drive.google.com/open?id=15NpPvpW-74Qm1gsSB74pTi1mz5rmxlFb) with `KerasModelImport.importKerasModelAndWeights(modelPath)`.  The model is a CNN text classifier similar to the sentence classification example.  Import results in the following error:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Double
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasInitilizationUtils.mapWeightInitialization(KerasInitilizationUtils.java:105)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasInitilizationUtils.getWeightInitFromConfig(KerasInitilizationUtils.java:223)
        at org.deeplearning4j.nn.modelimport.keras.layers.embeddings.KerasEmbedding.<init>(KerasEmbedding.java:109)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:261)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:305)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:144)
```

The model includes an embedding layer with a large constant initializer, which causes the same problem as mentioned in #4744.  To get the ClassCastException I had to build a local version of deeplearning4j-modelimport, though oddly I did not have to edit the "1000" constant used as the fix in  #4744.  Should I be doing something differently, either on the Keras side or the dl4j side, to deal with large constant initializers?

**Comment by maxpumperla** [comment]
have you tried snapshots?

**Comment by ibnopcit** [comment]
Same behavior in 1.0.0-SNAPSHOT.

**Comment by agibsonccc** [comment]
Closing due to issue age. If there's a similar issue, please re open.
