### ISSUE TITLE
ND4J Tests: Some tests can stall indefinitely

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#6514]
Something we've seen on CI but I managed to reproduce locally on my Linux machine...

Test is proceeding as normal, then just stops.
```
o.n.l.a.o.DynamicCustomOp - Op <permute>, isInplace: false
o.n.a.s.SameDiff - Step: 2; Executing op [std] for node [std]
o.n.a.v.GradCheckUtil - Param 56 (in[2,3,1]) passed: grad= 0.019895365853278474, numericalGrad= 0.019895367131539388, relError= 3.212458826208967E-8
o.n.a.s.SameDiff - Step: 1; Executing op [permute] for node [permute]
o.n.l.a.o.DynamicCustomOp - Op <permute>, isInplace: false
o.n.a.s.SameDiff - Step: 2; Executing op [std] for node [std]
```

We've had CI block like this for 10+ hours (until we killed it).

JStack output is... interesting... logger is blocking on file writing??? (Edit: and it's been at the exact same point for the last 20+ minutes when I've checked the stack traces)
```
"main" #1 prio=5 os_prio=0 tid=0x00007f509c00a800 nid=0x7eb9 runnable [0x00007f50a51d1000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	- locked <0x00000005c00f7d88> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:482)
	- locked <0x00000005c0049e28> (a java.io.PrintStream)
	at org.apache.maven.surefire.booter.ForkingRunListener.writeTestOutput(ForkingRunListener.java:181)
	- locked <0x00000005c0049e28> (a java.io.PrintStream)
	at org.apache.maven.surefire.report.ConsoleOutputCapture$ForwardingPrintStream.write(ConsoleOutputCapture.java:63)
	at ch.qos.logback.core.joran.spi.ConsoleTarget$1.write(ConsoleTarget.java:37)
	at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:199)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.debug(Logger.java:494)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:10231)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResult(SameDiff.java:9299)
	at org.nd4j.autodiff.validation.GradCheckUtil.checkGradients(GradCheckUtil.java:313)
	at org.nd4j.autodiff.validation.GradCheckUtil.checkGradients(GradCheckUtil.java:182)
	at org.nd4j.autodiff.validation.OpValidation.validateHelper(OpValidation.java:187)
	at org.nd4j.autodiff.validation.OpValidation.validate(OpValidation.java:114)
	at org.nd4j.autodiff.validation.OpValidation.validate(OpValidation.java:109)
	at org.nd4j.autodiff.opvalidation.TransformOpValidation.testSpaceToDepth(TransformOpValidation.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

   Locked ownable synchronizers:
	- <0x00000005c00bb0e8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

Aha! Link: https://skymindai.aha.io/features/ND4J-153

**Comment by saudet** [comment]
It could be the machines running out of memory and getting stuck trying to do GC. @sshepel is currently debugging why the -Xmx flag doesn't seem to be working for CI on the Linux machines.

**Comment by AlexDBlack** [comment]
Given the stack trace GC wouldn't be my first guess. But maybe I'll experiment with Xmx and see if it makes any difference.
```
at java.io.FileOutputStream.writeBytes(Native Method)
```
