### ISSUE TITLE
Error executing imported Keras model whith reshape and LSTM

### ISSUE THREAD

**Issue by TristanDupontICE** [eclipse/deeplearning4j#6700]
#### Running an imported Keras model which contains a reshape and a LSTM throws an exception

I am able to import the following Keras model [keras-model.zip](https://github.com/deeplearning4j/deeplearning4j/files/2571390/keras-model.zip) but I'm not able to use it.

```java
final ComputationGraph computationGraph = KerasModelImport.importKerasModelAndWeights(
        "keras-model.h5", false
);
System.out.println(computationGraph.summary());
final INDArray inputArray = Nd4j.rand(1, 3);
computationGraph.outputSingle(inputArray);
```

The summary of the ComputationGraph:
```
===========================================================================================================
VertexName (VertexType)          nIn,nOut   TotalParams   ParamsShape                         Vertex Inputs
===========================================================================================================
input_1 (InputVertex)            -,-        -             -                                   -            
dense_1 (DenseLayer)             3,10       40            W:{3,10}, b:{1,10}                  [input_1]    
reshape_1 (PreprocessorVertex)   -,-        -             -                                   [dense_1]    
lstm_1 (LastTimeStepLayer)       5,32       4864          W:{5,128}, RW:{32,128}, b:{1,128}   [reshape_1]  
dense_2 (DenseLayer)             32,1       33            W:{32,1}, b:{1,1}                   [lstm_1]     
-----------------------------------------------------------------------------------------------------------
            Total Parameters:  4937
        Trainable Parameters:  4937
           Frozen Parameters:  0
===========================================================================================================
```

The exception when the imported graph is used:
```
Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Received input with size(1) = 2 (input array shape = [1, 2, 5]); input.size(1) must match layer nIn size (nIn = 5)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:188)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:163)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activate(LSTM.java:140)
	at org.deeplearning4j.nn.layers.recurrent.LastTimeStepLayer.activate(LastTimeStepLayer.java:80)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2316)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1779)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1761)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1747)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1628)
```

This bug is very similar with the issue #4556 but the solution cannot be applied. The solution was to process the data before injecting them in the graph. In this case I can't do this the reshape + LSTM is not at the beginning of my graph.

We should be able to import or convert this Keras model in order to use it in dl4j.

#### Version Information

* Deeplearning4j version : 1.0.0-beta3
* Platform information : Ubuntu 16.04.5 LTS
* CUDA version : None
* NVIDIA driver version : None
* Keras version : 2.2.4

**Comment by agibsonccc** [comment]
Closing due to how old this is. It's likely related to our NWC/NCW support. We should be fine with this now. For anyone in the future, please open a new issue if you run in to something similar.
