### ISSUE TITLE
Cannot run Keras LSTM model with attention mechanism

### ISSUE THREAD

**Issue by mcao610** [eclipse/deeplearning4j#6801]
java.lang.IllegalStateException: Input shape [1, 100, 16] and output shape[1] do not match
	at org.deeplearning4j.nn.modelimport.keras.preprocessors.ReshapePreprocessor.preProcess(ReshapePreprocessor.java:102)
	at org.deeplearning4j.nn.graph.vertex.impl.PreprocessorVertex.doForward(PreprocessorVertex.java:60)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2287)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1698)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1675)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1605)
	at com.ibm.mobility.cr.predictor.lstm.LSTMKerasModel.predict(LSTMKerasModel.java:79)
	at com.ibm.mobility.cr.predictor.lstm.Predictor.predict(Predictor.java:72)
	at kerasToDl4j.PredTestCaseSample.main(PredTestCaseSample.java:27)

==================
It seems there is something wrong with the reshape layer. I merged the last two dimensions of a vector in Keras using reshape (also tries flatten), but dl4j always gives me this exception is run time. (the code is good on Keras)

Keras code:
```
        # compute importance for each step
        attention = Dense(1, activation='tanh')(activations)
        attention = Flatten()(attention)
        attention = Activation('softmax')(attention)
        attention = RepeatVector(100)(attention)
        attention = Permute([2, 1])(attention)

        sent_representation = multiply([activations, attention])
        sent_representation = Lambda(lambda xin: K.sum(xin, axis=-2), output_shape=(100,))(sent_representation)

        x = Dense(64, activation='linear')(sent_representation)
```

**Comment by maxpumperla** [comment]
@CadenC thanks for reporting. I suspect this is the same problem as this one https://github.com/deeplearning4j/deeplearning4j/issues/6700. Will let you know once I know more.

**Comment by agibsonccc** [comment]
Should be fixed by now, if not open a new issue.
