### ISSUE TITLE
arbiter UI: dropout ParameterSpace json convert exception

### ISSUE THREAD

**Issue by coolbeevip** [eclipse/deeplearning4j#6879]
my code
```java
ParameterSpace<Double> dropoutHyperparam = new ContinuousParameterSpace(0.1, 0.5);
...
...
MultiLayerSpace hyperparameterSpace = new MultiLayerSpace.Builder()
        .seed(1234567)
        .activation(activationInLayerHyperparam)
        .weightInit(weightInitHyperparam)
        .l2(l2Hyperparam)
        .updater(updaterHyperparam)
        .dropOut(dropoutHyperparam)
        .addLayer(new DenseLayerSpace.Builder()
                .nIn(numInputs)
                .activation(activationHiddenLayerHyperparam)
                .nOut(layerSizeHyperparam)
                .build())
        .addLayer(new OutputLayerSpace.Builder()
                .nOut(outputNum)
                .activation(activationOutLayerHyperparam)
                .lossFunction(lossFunctionOutLayerHyperparam)
                .build())
        .numEpochs(10)
        .build();
```

exception stack

```shell
}; line: 17, column: 74] (through reference chain: org.deeplearning4j.arbiter.optimize.config.OptimizationConfiguration["candidateGenerator"]->org.deeplearning4j.arbiter.MultiLayerSpace["dropout"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:124) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:169) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:124) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:124) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:169) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:124) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:966) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-1.0.0-beta3.jar:na]
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-1.0.0-beta3.jar:na]
	at org.deeplearning4j.arbiter.ui.misc.JsonMapper.fromJson(JsonMapper.java:68) ~[arbiter-ui_2.11-1.0.0-beta3.jar:na]
	... 32 common frames omitted

2018-12-17 16:24:42.075 ERROR 41983 --- [t-dispatcher-49] application                              : 

! @7a9ca7p3g - Internal server error, for (GET) [/arbiter/summary] ->
 

play.api.UnexpectedException: Unexpected exception[InvocationTargetException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.12.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.12.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.12.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.12.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [scala-library-2.11.12.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36) [scala-library-2.11.12.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44) [scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252) [scala-library-2.11.12.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157) [scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.12.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.16.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.16.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.12.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:66) ~[play-java_2.11-2.4.8.jar:2.4.8]
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:62) ~[play-java_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.8.jar:2.4.8]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.12.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[play-iteratees_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.12.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.12.jar:na]
	... 6 common frames omitted
Caused by: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.arbiter.conf.dropout.DropoutSpace<org.deeplearning4j.nn.conf.dropout.IDropout>]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {
  "@class" : "org.deeplearning4j.arbiter.optimize.config.OptimizationConfiguration",
  "candidateGenerator" : {
    "@class" : "org.deeplearning4j.arbiter.optimize.generator.RandomSearchGenerator",
    "initDone" : true,
    "parameterSpace" : {
      "@class" : "org.deeplearning4j.arbiter.MultiLayerSpace",
      "activationFunction" : {
        "@class" : "org.deeplearning4j.arbiter.adapter.ActivationParameterSpaceAdapter",
        "activation" : {
          "@class" : "org.deeplearning4j.arbiter.optimize.parameter.discrete.DiscreteParameterSpace",
          "values" : [ "LEAKYRELU", "SIGMOID", "TANH" ],
          "index" : 0
        }
      },
      "dropout" : {
        "@class" : "org.deeplearning4j.arbiter.conf.dropout.DropoutSpace",
        "dropout" : {
          "@class" : "org.deeplearning4j.arbiter.optimize.parameter.continuous.ContinuousParameterSpace",
          "distribution" : {
            "distribution" : "UniformRealDistribution",
            "lower" : 0.1,
            "upper" : 0.5
          },
          "index" : 4
        }
      },
```

**Comment by AlexDBlack** [comment]
Is this with 1.0.0-beta3?
If not, try upgrading... there were a couple of Arbiter dropout fixes in 1.0.0-beta3.
