### ISSUE TITLE
Add Dropout with cudnn got some error

### ISSUE THREAD

**Issue by liuxun666** [eclipse/deeplearning4j#7161]
#### Issue Description

To add dropout parameter to the ComputationGraph which running on cudnn got cuDNN status = 8: CUDNN_STATUS_EXECUTION_FAILED, and The program works without this parameter.

> Exception in thread "main" java.lang.RuntimeException: cuDNN status = 8: CUDNN_STATUS_EXECUTION_FAILED
        at org.deeplearning4j.nn.layers.BaseCudnnHelper.checkCudnn(BaseCudnnHelper.java:44)
        at org.deeplearning4j.nn.layers.dropout.CudnnDropoutHelper.applyDropout(CudnnDropoutHelper.java:181)
        at org.deeplearning4j.nn.conf.dropout.Dropout.applyDropout(Dropout.java:137)
        at org.deeplearning4j.nn.layers.AbstractLayer.applyDropOutIfNecessary(AbstractLayer.java:302)
        at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:287)
        at org.deeplearning4j.nn.layers.BaseOutputLayer.preOutput2d(BaseOutputLayer.java:363)
        at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:163)
        at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:148)
        at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2621)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1369)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1329)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1149)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1098)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1065)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:999)
        at dl4j.Testdl4j.testDropOut(Testdl4j.java:69)
        at dl4j.Testdl4j.main(Testdl4j.java:44)

there is my code:
```
private static void testDropOut() {
        ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
                .dropOut(0.5)
                .updater(new Adam())
                .graphBuilder()
                .addInputs("input")
                .addLayer("output", new OutputLayer.Builder()
                        .lossFunction(new LossNegativeLogLikelihood())
                        .nIn(2)
                        .nOut(2)
                        .activation(Activation.SOFTMAX)
                        .build(), "input")
                .setOutputs("output")
                .build();
        ComputationGraph graph = new ComputationGraph(config);
        graph.init();
        INDArray x1 = Nd4j.create(new double[]{2, 2});
        INDArray x2 = Nd4j.create(new double[]{-1, 0});
        INDArray y1 = Nd4j.create(new double[]{1, 0});
        INDArray y2 = Nd4j.create(new double[]{0, 1});
        DataSet d1 = new DataSet(x1, y1);
        DataSet d2 = new DataSet(x2, y2);
        graph.fit(new ListDataSetIterator(Arrays.asList(d1, d2)));
        INDArray[] output = graph.output(x1);
        System.out.println(Arrays.toString(output[0].toDoubleVector()));
    }

    private static void testWithOutDropOut(){
        ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
                .updater(new Adam())
                .graphBuilder()
                .addInputs("input")
                .addLayer("output", new OutputLayer.Builder()
                        .lossFunction(new LossNegativeLogLikelihood())
                        .nIn(2)
                        .nOut(2)
                        .activation(Activation.SOFTMAX)
                        .build(), "input")
                .setOutputs("output")
                .build();
        ComputationGraph graph = new ComputationGraph(config);
        graph.init();
        INDArray x1 = Nd4j.create(new double[]{2, 2});
        INDArray x2 = Nd4j.create(new double[]{-1, 0});
        INDArray y1 = Nd4j.create(new double[]{1, 0});
        INDArray y2 = Nd4j.create(new double[]{0, 1});
        DataSet d1 = new DataSet(x1, y1);
        DataSet d2 = new DataSet(x2, y2);
        graph.fit(new ListDataSetIterator(Arrays.asList(d1, d2)));
        INDArray[] output = graph.output(x1);
        System.out.println(Arrays.toString(output[0].toDoubleVector()));
    }

```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta3
* platform information (OS, etc): os: centos7 64bit
* Cores: [8]; Memory: [6.9GB];
* Device Name: [GeForce RTX 2080 Ti]; CC: [7.5]; Total/free memory: [11523260416]
* CUDA version: 9.0
* cudnn version: 7.0.5
* NVIDIA driver version: 410.78

**Comment by AlexDBlack** [comment]
Thanks for the issue.
I'm not able to reproduce this on my Titan X (Pascal gen) on Windows 10 in either 1.0.0-beta3 or current snapshots. I'll try Linux later.
I do wonder if this is an issue on the cuDNN side - perhaps try upgrading to the latest CUDA 10 + cuDNN and see if it still persists?
