### ISSUE TITLE
IntervalIndex.reverse() does not work

### ISSUE THREAD

**Issue by nicoulaj** [eclipse/deeplearning4j#7276]
#### Issue Description
This test:

    @Test
    public void testReverseIntervalIndex() {

        INDArray array = Nd4j.create(new double[] { 0, 1, 2, 3, 4, 5 });

        INDArrayIndex interval = NDArrayIndex.interval(1, 4);
        interval.reverse();

        array.get(interval).toString();
    }

throws:
```
java.lang.IndexOutOfBoundsException: 6
	at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:94)
	at org.bytedeco.javacpp.indexer.DoubleRawIndexer.get(DoubleRawIndexer.java:59)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getDouble(BaseDataBuffer.java:1239)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:682)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1917)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:4435)
	at org.nd4j.linalg.string.NDArrayStrings.vectorToString(NDArrayStrings.java:243)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:182)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:150)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:127)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:5774)
```

From reading `IntervalIndex`, it seems `next()` does not invert `stride`, not sure how this is supposed to work.

#### Version Information

* Deeplearning4j version: sonatype repo 1.0.0 snapshot: 1.0.0-20190308.084722-15882
* platform information (OS, etc): linux x86_64
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

Aha! Link: https://skymindai.aha.io/features/ND4J-89

**Comment by AlexDBlack** [comment]
@rnett re: https://github.com/deeplearning4j/deeplearning4j/pull/7370#issuecomment-477081839
> Looking into things, it looks like reverse needs some significant work.

Yeah, unfortunately I'm not surprised in this case, given there aren't other tests (that I could see).

Thinking about it now, I can see 2 possible solutions here that might be easier to maintain:

1) We drop reverse() entirely, add an INDArray.reverse(int... axis) method to use instead
2) Keep reverse(), add some special cases in the get() method; get the non-reversed view array, then do reverse along the specified axis.

Views with reversed axis (negative strides) are conceptually possible, but not really worth us implementing it any time soon, so neither of those options would support views.

**Comment by rnett** [comment]
Its not terribly hard to fix as is, you just have to sometimes switch the starting index and change a few checks.

I haven't been able to run all of the tests, but it at least gets the correct indexes.  I don't think I would need to touch get?
