### ISSUE TITLE
ND4J CUDA: Legacy ConcatFloat(...) failedError code [4]

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#7465]
Reported in Gitter:
```
Mike Chen @qinritukou Apr 07 01:33
hi guys, do you know what makes error below ?
Exception in thread "main" java.lang.RuntimeException: Legacy ConcatFloat(...) failedError code [4]
at org.nd4j.nativeblas.Nd4jCuda$NativeOps.concatFloat(Native Method)
at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:481)
at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5205)
at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:401)
at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:360)
at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:327)
at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:213)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:365)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:440)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:84)
Thanks ahead.
```

I assume this in on snapshots, given we recently had some concat changes there?

**Comment by raver119** [comment]
No, he's not on snapshots. `concatFloat`. That assumes stable release.
