### ISSUE TITLE
Error importing keras BiLSTM model

### ISSUE THREAD

**Issue by lo2aayy** [eclipse/deeplearning4j#7565]
#### Issue Description
When trying to import the following model from keras:
![image](https://user-images.githubusercontent.com/23140431/56293663-d1079800-6129-11e9-84ec-14276297fc03.png)

I get the following error:
`Exception in thread "main" java.lang.IllegalStateException: Invalid input for RNN layer (layer name = "lstm_1"): input type is null
	at org.deeplearning4j.nn.conf.layers.InputTypeUtil.getPreprocessorForInputTypeRnnLayers(InputTypeUtil.java:475)
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLSTM.getInputPreprocessor(KerasLSTM.java:272)
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLSTM.getOutputType(KerasLSTM.java:236)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:304)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:179)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:144)
	at de.averbis.textanalysis.dl4j.RunTFModelInDL4J.main(RunTFModelInDL4J.java:38)`

#### Version Information

Deeplearning4j version: 1.0.0-beta3
platform information: Linux CentOS

NB: Kindly find the model attached.
[model.zip](https://github.com/deeplearning4j/deeplearning4j/files/3090017/model.zip)

**Comment by agibsonccc** [comment]
Closing, likely fixed by now.
