### ISSUE TITLE
Error Importing Keras Model Android

### ISSUE THREAD

**Issue by gulzainali98** [eclipse/deeplearning4j#7644]
I am trying to import keras model into android and getting a missing HDF5 file. 

Here is the stack trace:
2019-05-01 20:18:21.506 18398-18398/com.app.kerasdeeplearning E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.kerasdeeplearning, PID: 18398
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bytedeco/javacpp/hdf5;
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<clinit>(Hdf5Archive.java:57)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.weightsHdf5FilenameNoRoot(KerasModelBuilder.java:267)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:254)
        at com.app.kerasdeeplearning.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2903)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3058)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.hdf5" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.app.kerasdeeplearning-x5Kq8C6_wqlpxXnEutne4w==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.kerasdeeplearning-x5Kq8C6_wqlpxXnEutne4w==/lib/arm64, /data/app/com.app.kerasdeeplearning-x5Kq8C6_wqlpxXnEutne4w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<clinit>(Hdf5Archive.java:57) 
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.weightsHdf5FilenameNoRoot(KerasModelBuilder.java:267) 
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:254) 
        at com.app.kerasdeeplearning.MainActivity.onCreate(MainActivity.java:39) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2903) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3058) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

**Comment by saudet** [comment]
Unfortunately, HDF5 doesn't support Android. You'll need to import on the
desktop and load the resulting DL4J model on Android.

**Comment by AlexDBlack** [comment]
We should probably add some sort of check/exception at the DL4J level for this (in Keras import methods), rather than having users run into this...

**Comment by saudet** [comment]
JavaCPP already does throw a proper `java.lang.UnsatisfiedLinkError: Platform "android-x86_64" not supported by org.bytedeco.hdf5` message. Which version of DL4J are you using @gulzainali98?

**Comment by yilmazo** [comment]
> Unfortunately, HDF5 doesn't support Android. You'll need to import on the desktop and load the resulting DL4J model on Android.

how can I do this @saudet ? I tried writing object to a file on desktop using ObjectOutputStream and importing that file on android using ObjectInputStream, and got the same error.

**Comment by saudet** [comment]
@yilmazo https://deeplearning4j.org/docs/latest/deeplearning4j-nn-model-persistence
