### ISSUE TITLE
SameDiff gather() execBackwards

### ISSUE THREAD

**Issue by lastrealklaus** [eclipse/deeplearning4j#7852]
when executing sd.execBackwards an graph with gather i get a NullPointerException when using a sdvariable of type ARRAY for gather indices.

		var sd = SameDiff.create();

		var input = sd.var(Nd4j.rand(new int[] { 2, 5 }, new NormalDistribution()).dup());
		var indices = sd.var(Nd4j.create(new float[] { 3 })).castTo(DataType.INT);

		var logsoftmax = input.sub("logsoftmax", sd.math().log(sd.math().exp(input).sum()));
		var gathered = sd.gather(logsoftmax, indices, 1);

		sd.exec(null, gathered.getVarName());
		sd.setLossVariables(gathered.getVarName());
		sd.execBackwards(null);

```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.impl.shape.Gather.doDiff(Gather.java:153)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:608)
	at org.nd4j.autodiff.samediff.SameDiff$1.define(SameDiff.java:3853)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3426)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3411)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:3595)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:3456)
```

when i substitute the sdvariable for indices with an int array in the above code I get an IllegalArgumentException:

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid index: must be 0 to numArgs (0 <= idx < 1)
	at org.nd4j.base.Preconditions.throwEx(Preconditions.java:636)
	at org.nd4j.base.Preconditions.checkArgument(Preconditions.java:73)
	at org.nd4j.autodiff.functions.DifferentialFunction.arg(DifferentialFunction.java:523)
	at org.nd4j.linalg.api.ops.impl.shape.Gather.doDiff(Gather.java:150)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:608)
	at org.nd4j.autodiff.samediff.SameDiff$1.define(SameDiff.java:3853)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3426)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3411)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:3595)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:3456)
```

used version: todays 1.0.0-snapshot

**Comment by raver119** [comment]
Thanks for highlighting this issue!
