### ISSUE TITLE
DL4JInvalidConfigException nIn and nOut must be > 0

### ISSUE THREAD

**Issue by Lezhik** [eclipse/deeplearning4j#7903]
#### Issue Description
I create simple CNN network based on documentation: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-multilayernetwork

```
    public static void main(String[] args) {
        MultiLayerConfiguration.Builder builder = new NeuralNetConfiguration.Builder()
                .seed(1L)
                .l2(0.0005)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(new Nesterovs(0.01, 0.9))
                .list()
                .layer(0, new ConvolutionLayer.Builder(5, 5)
                        //nIn and nOut specify depth. nIn here is the nChannels and nOut is the number of filters to be applied
                        .nIn(3)
                        .stride(1, 1)
                        .nOut(20)
                        .activation(Activation.IDENTITY)
                        .build())
                .layer(1, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                        .kernelSize(2,2)
                        .stride(2,2)
                        .build())
                .layer(2, new ConvolutionLayer.Builder(5, 5)
                        //Note that nIn need not be specified in later layers
                        .stride(1, 1)
                        .nOut(50)
                        .activation(Activation.IDENTITY)
                        .build())
                .layer(3, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                        .kernelSize(2,2)
                        .stride(2,2)
                        .build())
                .layer(4, new DenseLayer.Builder()
                        .activation(Activation.SOFTMAX)
                        .nOut(500)
                        .build())
                .layer(5, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                        .nOut(10)
                        .activation(Activation.SOFTMAX)
                        .build());
        MultiLayerNetwork net = new MultiLayerNetwork(builder.build());
        net.init();
    }
```

I got an exception for this code:
```
Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidConfigException: ConvolutionLayer (index=2, name=layer2) nIn=0, nOut=50; nIn and nOut must be > 0
    	at org.deeplearning4j.nn.conf.layers.LayerValidation.assertNInNOutSet(LayerValidation.java:54)
    	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:166)
    	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:707)
    	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:600)
    	at org.libdrasil.Test.main(Test.java:58)

```
Expected behavior: nIn need not be specified in later layers

#### Version Information

* Deeplearning4j version
    compile 'org.nd4j:nd4j-native-platform:1.0.0-beta4'
    compile 'org.deeplearning4j:deeplearning4j-core:1.0.0-beta4'
    compile 'org.deeplearning4j:deeplearning4j-nlp:1.0.0-beta4'

* platform information (OS, etc)
Windows 8, java 1.8

**Comment by AlexDBlack** [comment]
Use `.setInputType(InputType.convolutional(height, width, 3)`.
