### ISSUE TITLE
DL4J Keras Import: Import TCN (causal conv1d) keras model to DL4J

### ISSUE THREAD

**Issue by sanpie90** [eclipse/deeplearning4j#7968]
Hi,

I am trying to import TCN model implemented with keras-tcn https://github.com/philipperemy/keras-tcn library 

While importing : 

`    val modelKerasTcn = KerasModelImport.importKerasModelAndWeights("data/model_tcn.h5", false)
`

I get an error: 

`Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported convolution border mode: causal. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.convolutional.KerasConvolutionUtils.getConvolutionModeFromConfig(KerasConvolutionUtils.java:269)
	at org.deeplearning4j.nn.modelimport.keras.layers.convolutional.KerasConvolution1D.<init>(KerasConvolution1D.java:107)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:233)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:155)`

#### Version Information
DL4J : Version 1.0.0-beta4

Is it something you consider to include in your future release? 

Thank you,
Sandra

**Comment by trokas** [comment]
I am at the same spot - trying to deploy model, which uses keras-tcn via spark-submit. It's a pity that TCN's don't work directly. Maybe someone has figured out a solution?
`... org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported convolution border mode: causal. ...`

**Comment by AlexDBlack** [comment]
We have plans to implement causal convolutional nets already (see this issue):
https://github.com/eclipse/deeplearning4j/issues/7629

However, we won't be supporting 3rd party / custom Keras layers (like the one you are trying to import) any time soon.

For those two reasons (duplicate issue + not supporting custom/3rd party Keras extensions) I'll close this.

**Comment by AlexDBlack** [comment]
Actually, looks like causal conv1d *is* supported officially in Keras (it wasn't when I looked in the past):

https://keras.io/backend/#conv1d
https://github.com/keras-team/keras/search?q=causal&unscoped_q=causal
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D

So the 3rd party library isn't relevant to this request, given it's also an official feature.

**Comment by arnauddelaunay** [comment]
+1
I'm facing the same issue !

**Comment by AlexDBlack** [comment]
Causal Conv1d support was added here, for both DL4J and DL4J Keras import: https://github.com/KonduitAI/deeplearning4j/pull/107

It will be merged back to eclipse/deeplearning4j soon, and will be in the upcoming 1.0.0-beta6 release.
