### ISSUE TITLE
Libng4j graph executioner: Graph is not topsorted for Keras RNNs

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7974]
Not particularly urgent, this is just to keep track of the issue.

When importing a Keras RNN layer (tested w/ GRU and LSTM) via the tensorflow import and running the graph w/ Libnd4j's graph executioner, I get the error `Graph wasn't topsorted`.

To reproduce: use `org.nd4j.imports.TFGraphs.TFGraphTestZooModels` (need deeplearning4j/dl4j-test-resources#203 until its merged) and remove `PorV-RNN` (or one of the others with it) from `IGNORE_REGEXES_LIBND4J_EXEC_ONLY`.

Stacktrace:
```java
o.n.i.T.TFGraphTestZooModels - ----- Libnd4j Exec: PorV-RNN -----
o.n.i.T.TFGraphTestAllHelper - 
	RUNNING TEST PorV-RNN...
o.n.a.e.NativeGraphExecutioner - Buffer length: 524288

java.lang.RuntimeException: Graph wasn't toposorted

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.executeFlatGraph(Native Method)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.executeFlatGraph(Nd4jCpu.java:690)
	at org.nd4j.autodiff.execution.NativeGraphExecutioner.executeGraph(NativeGraphExecutioner.java:103)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.getGraphAfterExec(TFGraphTestAllHelper.java:398)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:144)
	at org.nd4j.imports.TFGraphs.TFGraphTestZooModels.testOutputOnly(TFGraphTestZooModels.java:292)
```

**Comment by AlexDBlack** [comment]
There's a number of others that result is this same exception (loops, etc where no topological sort is possible due to cycles in the graph).
Libnd4j graph execution needs a pass, for this, it's a known issue.
