### ISSUE TITLE
Libnd4j/Nd4j ResizeNearestNeighbor missing calculateOutputDataTypes

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#7976]
When trying to import `ResizeNearestNeighbor` from tensorflow, I get `java.lang.UnsupportedOperationException: calculateOutputDataTypes() has not been implemented for org.nd4j.linalg.api.ops.impl.image.ResizeNearestNeighbor`.

To reproduce:
```java
@Test
public void testResize(){

    INDArray out = Nd4j.create(DataType.FLOAT, 2, 4, 5);
    DynamicCustomOp c = new ResizeNearestNeighbor();

    c.addInputArgument(
            Nd4j.rand(DataType.FLOAT, 4, 4, 3)
    );
    c.addIArgument(4, 3);
    c.addOutputArgument(out);
    c.calculateOutputDataTypes(new ArrayList<>());
}
```
I doubt this is valid input, but it raises the error.

Or you can use `org.nd4j.imports.TFGraphs.TFGraphTestZooModels` and un-ignore `deeplabv3_xception_ade20k_train`

Stacktrace:
```
ava.lang.UnsupportedOperationException: calculateOutputDataTypes() has not been implemented for org.nd4j.linalg.api.ops.impl.image.ResizeNearestNeighbor

	at org.nd4j.autodiff.functions.DifferentialFunction.calculateOutputDataTypes(DifferentialFunction.java:802)
	at org.nd4j.autodiff.samediff.internal.DataTypesSession.getOutputs(DataTypesSession.java:84)
	at org.nd4j.autodiff.samediff.internal.DataTypesSession.getOutputs(DataTypesSession.java:38)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:305)
	at org.nd4j.autodiff.samediff.SameDiff.calculateOutputDataTypes(SameDiff.java:5465)
	at org.nd4j.autodiff.samediff.SameDiff.calculateOutputDataTypes(SameDiff.java:5451)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:349)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:90)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:83)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper$DefaultGraphLoader.apply(TFGraphTestAllHelper.java:90)
	at org.nd4j.imports.TFGraphs.TFGraphTestZooModels$RemoteCachingLoader.apply(TFGraphTestZooModels.java:210)
	at org.nd4j.imports.TFGraphs.TFGraphTestZooModels$RemoteCachingLoader.apply(TFGraphTestZooModels.java:135)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.getGraphAfterExec(TFGraphTestAllHelper.java:369)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:144)
	at org.nd4j.imports.TFGraphs.TFGraphTestZooModels.testOutputOnly(TFGraphTestZooModels.java:282)
```

**Comment by AlexDBlack** [comment]
This is java level issue - the fix should be simple (copy/paste as per here):
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/image/ResizeBilinear.java#L78-L84

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/image/ResizeNearestNeighbor.java
