### ISSUE TITLE
no nd4jcuda in java.library.path

### ISSUE THREAD

**Issue by cacophany53** [eclipse/deeplearning4j#7990]
I'm attempting to run a simple DL4J example using CUDA 10.1.

My POM dependencies:

```
<dependencies>
	  <dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-core</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
 	<dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-cuda-10.1</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
	<dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-api</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-cuda-10.1-platform</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
	  </dependency>
	</dependencies>
```

CUDA 10.1 is installed:

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168
```

Platform is Windows 10 64.
Graphics Card is NVIDIA GeForce GTX 1050 Ti (4G).

Note that I'm running on a laptop that ALSO has an integrated display adapter: Intel HD Graphics 630. I've tried disabling this (via Device Manager) but the result is the same.

The error I am getting is as follows:

```
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:68)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:36)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1077)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:457)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:46)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1033)
	... 25 more
```

**Comment by saudet** [comment]
Add the redist artifacts as well, that should take care of this:
https://github.com/bytedeco/javacpp-presets/tree/1.5/cuda#the-pomxml-build-file

@crockpotveggies What do you need to do to get this page updated? It never gets updated
https://deeplearning4j.org/docs/latest/deeplearning4j-config-cudnn

**Comment by cacophany53** [comment]
Thanks saudet.

Unfortunately I'm still getting the same error.
Do you think it might have something to do with the Integrated Graphics that's also in the laptop?

My POM:

```
<dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-core</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
 	<dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-cuda-10.1</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
	<dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-api</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-cuda-10.1-platform</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
	  </dependency>
	  <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>linux-x86_64-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>linux-ppc64le-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>macosx-x86_64-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>windows-x86_64-redist</classifier>
        </dependency>
```

**Comment by cacophany53** [comment]
Note that when I tried running with native (not cuda) it worked fine.

**Comment by cacophany53** [comment]
I was using an old version of eclipse.
I've now upgraded to the newest version.
My POM now looks like this:

```
 <dependencies>
	  <dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-core</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
	    <groupId>org.deeplearning4j</groupId>
	    <artifactId>deeplearning4j-datavec-iterators</artifactId>
	    <version>1.0.0-beta4</version>
	</dependency>
	<dependency>
	    <groupId>org.deeplearning4j</groupId>
	    <artifactId>deeplearning4j-nn</artifactId>
	    <version>1.0.0-beta4</version>
	</dependency>
 	<dependency>
	      <groupId>org.deeplearning4j</groupId>
	      <artifactId>deeplearning4j-cuda-10.1</artifactId>
	      <version>1.0.0-beta4</version>
	  </dependency>
	<dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-api</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
		 <groupId>org.nd4j</groupId>
		 <artifactId>nd4j-cuda-10.1-platform</artifactId>
		 <version>1.0.0-beta4</version>
	  </dependency>
	  <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>linux-x86_64-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>linux-ppc64le-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>macosx-x86_64-redist</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda</artifactId>
            <version>10.1-7.5-1.5</version>
            <classifier>windows-x86_64-redist</classifier>
        </dependency>
        <dependency> 
		    <groupId>ch.qos.logback</groupId> 
		    <artifactId>logback-classic</artifactId> 
		    <version>1.2.3</version> 
		</dependency>
	</dependencies>
```

Here are the "Maven Dependencies" for the project, according to eclipse:

![image](https://user-images.githubusercontent.com/52687078/60862756-f7892b00-a261-11e9-90cd-359671f38064.png)

Still getting the same error:

```
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1033)
	... 25 more
```

**Comment by saudet** [comment]
Could you with Maven on the command line? If that works, then it's just an issue with the Eclipse IDE, and you should report that issue over there.

**Comment by crockpotveggies** [comment]
@saudet we can actually make that a config option in the docs repo and that way everytime we autogen the docs with each commit/release it gets updated. That would be added here: https://github.com/deeplearning4j/deeplearning4j-docs/blob/master/_config.yml#L44

**Comment by saudet** [comment]
@crockpotveggies Ok, but how do we update that after the release, like now? I've updated it 2 months ago in the main repository, but it's not getting updated: https://github.com/eclipse/deeplearning4j/blob/_old/master/docs/deeplearning4j/templates/config-cudnn.md

**Comment by crockpotveggies** [comment]
@saudet let's ping @sshepel since that seems odd. Serhii is this rebuilding when Sam commits?

**Comment by saudet** [comment]
I'm sure it works for the snapshots, but the release? Where are we supposed to commit those updates? Do we need to just update the docs repo manually when that happens?

**Comment by cacophany53** [comment]
FYI my original issue is fixed. After executing from the command line, maven was complaining about some POMs:
```

[WARNING] The POM for org.deeplearning4j:deeplearning4j-core:jar:1.0.0-beta4 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.deeplearning4j:deeplearning4j-core:1.0.0-beta4
[FATAL] Non-parseable POM C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom: start tag not allowed in epilog but got p (position: END_TAG seen ...</reporting>\n</project>\n          <p... @538:13)  @ C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom, line 538, column 13

[WARNING] The POM for org.deeplearning4j:deeplearning4j-datavec-iterators:jar:1.0.0-beta4 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.deeplearning4j:deeplearning4j-datavec-iterators:1.0.0-beta4
[FATAL] Non-parseable POM C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom: start tag not allowed in epilog but got p (position: END_TAG seen ...</reporting>\n</project>\n          <p... @538:13)  @ C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom, line 538, column 13

[WARNING] The POM for org.deeplearning4j:deeplearning4j-nn:jar:1.0.0-beta4 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.deeplearning4j:deeplearning4j-nn:1.0.0-beta4
[FATAL] Non-parseable POM C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom: start tag not allowed in epilog but got p (position: END_TAG seen ...</reporting>\n</project>\n          <p... @538:13)  @ C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom, line 538, column 13

[WARNING] The POM for org.deeplearning4j:deeplearning4j-cuda-10.1:jar:1.0.0-beta4 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.deeplearning4j:deeplearning4j-cuda-10.1:1.0.0-beta4
[FATAL] Non-parseable POM C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom: start tag not allowed in epilog but got p (position: END_TAG seen ...</reporting>\n</project>\n          <p... @538:13)  @ C:\Users\Eternity\.m2\repository\org\deeplearning4j\deeplearning4j-parent\1.0.0-beta4\deeplearning4j-parent-1.0.0-beta4.pom, line 538, column 13

```

I checked them out and it looks like something weird happened to them, the </project> end tag appeared part way through the POM and then another one at the end.

I deleted everything from my .m2 repository and re-updated. Now everything is fine.
Thanks for your help.

**Comment by crockpotveggies** [comment]
@saudet snapshots should be going to the `_latest` folder because that's the "latest" release, so if they're not doing that already then let's chat with @sshepel https://github.com/deeplearning4j/deeplearning4j-docs/tree/master/docs
