### ISSUE TITLE
CUDA 10.1 Update 1 to be supported with the ND4j Backend

### ISSUE THREAD

**Issue by davids91** [eclipse/deeplearning4j#7998]
#### Issue Description
Downgrading to 10.1 (2019 feb update ) solved the below exception and Software works correctly.

#### Version Information
    compile 'org.deeplearning4j:deeplearning4j-core:1.0.0-beta4'
    compile group: 'org.nd4j', name: 'nd4j-api', version: '1.0.0-beta4'
    compile group: 'org.nd4j', name: 'nd4j-cuda-10.1', version: '1.0.0-beta4'
    compile group: 'org.nd4j', name: 'nd4j-cuda-10.1-platform', version: '1.0.0-beta4'

#### Additional Information

09:13:51.572 [JavaFX Application Thread] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
09:13:53.948 [JavaFX Application Thread] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
	at project.class1.<init>(StereoImageDisparityMap.java:62)
	at project.class1.<init>(StereoImageDisparityMap.java:20)
	at project.class1$Builder.build(StereoImageDisparityMap.java:160)
	at project.class2.loadCurrIter(StereoImgRecordReader.java:120)
	at project.class2.reset(StereoImgRecordReader.java:131)
	at project.class2.initialize(StereoImgRecordReader.java:60)
	at project.class2.<init>(StereoImgRecordReader.java:47)
	at project.MainFXMLController.resIsValid(MainFXMLController.java:354)
	at project.MainFXMLController.lambda$null$14(MainFXMLController.java:232)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5900)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5860)
	... 18 more
Caused by: java.lang.UnsatisfiedLinkError: no jnicusparse in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1077)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.cuda.global.cusparse.<clinit>(cusparse.java:15)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.cuda.global.cusolver.<clinit>(cusolver.java:19)
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.createNewSolverHandle(BasicContextPool.java:220)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:115)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:80)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:145)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:145)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:93)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.<init>(JCublasNDArrayFactory.java:85)
	... 23 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\***\.javacpp\cache\cuda-10.1-7.5-1.5-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jnicusparse.dll: The specified procedure could not be found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1316)

**Comment by raver119** [comment]
cc @sshepel @saudet

**Comment by saudet** [comment]
It's available for JavaCPP 1.5.1. @AlexDBlack Where should I send a pull request for that?

**Comment by AlexDBlack** [comment]
@saudet You mean which repo to update? At this point it probably doesn't make much difference, either eclipse/deeplearning4j or skymind/deeplearning4j
We need to merge/update both ways anyway soon...
