### ISSUE TITLE
Upsampling.getMemoryReport ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jxtps** [eclipse/deeplearning4j#8014]
#### Issue Description

Calling `Upsampling.getMemoryReport` leads to an `ArrayIndexOutOfBoundsException`: 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at org.deeplearning4j.nn.conf.layers.Upsampling2D.getMemoryReport(Upsampling2D.java:119)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.getMemoryReport(LayerVertex.java:147)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.getMemoryReport(ComputationGraphConfiguration.java:635)
``` 

Looking at [the source code](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Upsampling2D.java#L118), it currently reads: 
```scala
val im2colSizePerEx = c.getChannels() * outputType.getHeight() * outputType.getWidth() 
    * size[0] * size[1] * size[2];
```

Presumably it should be: 
```scala
val im2colSizePerEx = c.getChannels() * outputType.getHeight() * outputType.getWidth() 
    * size[0] * size[1];
```
(i.e. drop `* size[2]`) since the layer only has 2 dimensions.

**Comment by AlexDBlack** [comment]
Thanks for the issue/fix: https://github.com/eclipse/deeplearning4j/pull/8015
