### ISSUE TITLE
NullPointerException in createFromNpyFile

### ISSUE THREAD

**Issue by Belval** [eclipse/deeplearning4j#8021]
#### Issue Description

Please describe our issue, along with:
Expected behavior: The `INDArray` should be created
Encountered behavior: NullPointerException is thrown

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): Ubuntu 18.04
* CUDA version, if used: 10.1
* NVIDIA driver version, if in use: 418

#### Additional Information

Where applicable, please also provide:

Full log or exception stack trace

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getAllocationPoint(AtomicAllocator.java:519)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getAllocationPoint(AtomicAllocator.java:1048)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.targetDevice(BaseCudaDataBuffer.java:1559)
	at org.nd4j.linalg.memory.deallocation.DeallocatorService.pickObject(DeallocatorService.java:78)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:101)
	at org.nd4j.linalg.jcublas.buffer.CudaLongDataBuffer.<init>(CudaLongDataBuffer.java:45)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.create(CudaDataBufferFactory.java:550)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1474)
	at org.nd4j.nativeblas.BaseNativeNDArrayFactory.createFromNpyPointer(BaseNativeNDArrayFactory.java:134)
	at org.nd4j.nativeblas.BaseNativeNDArrayFactory.createFromNpyFile(BaseNativeNDArrayFactory.java:271)
	at org.nd4j.linalg.factory.Nd4j.createFromNpyFile(Nd4j.java:6362)
	at log320.pentai.AlphaPenteModel.metatrainFromBatches(AlphaPenteModel.java:208)
	at log320.pentai.App.main(App.java:50)
```

pom.xml file or similar (also in a Gist): https://gist.github.com/Belval/1858e7f7e31ec6b3eafe696e3b9de1ee

#### Problematic code

`INDArray inputs = Nd4j.createFromNpyFile(new File("batch-x-1.npy"));`

**Comment by raver119** [comment]
Is this empty array? If not - please post it here

**Comment by Belval** [comment]
It is indeed a zeroed array, but its shape is consistent:

```
>>> arr.shape
(1024, 3, 15, 15)
>>> np.sum(arr)
0.0
```

The .npy file can be downloaded here: http://nextcloud.belval.org/index.php/s/2May4eeqPLDwPY2

**Comment by raver119** [comment]
No, empty array means shape of the array contains zeros.

**Comment by Belval** [comment]
I tried with a smaller (256, 15, 15 , 3) array that had some values in it. Same result. Is there anything you'd like me to try?

**Comment by raver119** [comment]
No. Apparently there's some bug in CUDA backend.

**Comment by Belval** [comment]
I see, is there any temporary workaround I could implement until a fix added to the codebase?

**Comment by raver119** [comment]
Since that's CUDA backend, i'm afraid there's nothing you can do here until we're done with CUDA. Current snapshot is unstable for CUDA.

**Comment by raver119** [comment]
Issue is fixed. Thanks for highlighting.

**Comment by Belval** [comment]
Great! How can I get those changes?

**Comment by raver119** [comment]
> Since that's CUDA backend, i'm afraid there's nothing you can do here until we're done with CUDA. Current snapshot is unstable for CUDA.

Best thing you can do is just wait. We're almost done with CUDA, but it'll take some time to ensure all tests pass, all new ops are properly integrated and so on.

**Comment by Belval** [comment]
Wait for how long, do you have an estimate of some kind? This is fun an all but I can't just "not work" for a few days...

**Comment by raver119** [comment]
Maybe 2 days.  Maybe 3. Maybe 7. Hard to give precise date. Soon enough we hope.
