### ISSUE TITLE
ParallelWrapper appears to leak memory over epochs

### ISSUE THREAD

**Issue by jxtps** [eclipse/deeplearning4j#8023]
#### Issue Description

Using ParallelWrapper like so: 

```scala
      val par = new ParallelWrapper.Builder(network)
        .workers(workers)
        .prefetchBuffer(workers * 2)
        .averagingFrequency(1)
        .reportScoreAfterAveraging(true)
        .build()
      par.setListeners(statsStorage)
      for (i <- Range(0, epochs)) {
        println(s"$name running epoch $i...")
        par.fit(iter)
        iter.reset()
      }
```
It runs out of memory after about 3 epochs: 
```
Caused by: java.lang.RuntimeException: Failed to allocate 4194304 bytes from DEVICE [0] memory
	at org.nd4j.jita.memory.CudaMemoryManager.allocate(CudaMemoryManager.java:78)
	at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:224)
```

Monitoring the GPU RAM you can see how the RAM steps up with each epoch: 
![image](https://user-images.githubusercontent.com/90846/61417871-9c80b500-a8ad-11e9-8fa6-ee87c1677040.png)

However, if I change my recordReader such that it internally repeats instead of doing the outer epoch loop, then I don't run out of memory - it stays flat over all epochs: 
![image](https://user-images.githubusercontent.com/90846/61418364-241af380-a8af-11e9-9b14-b1f39333f8aa.png)
(stopped run manually after a while)

So it looks like `ParallelWrapper.fit()` leaks?!

#### Version Information

Please indicate relevant versions, including, if relevant:

DL4J 1.0 beta 4
Windows 10
Bytedeco: 10.1-7.5-1.5
NVIDIA driver: 425.25

**Comment by raver119** [comment]
I highly doubt that: PW doesn't allocate anything on its own. And the only problem we've been able to reproduce was caused by absence of full gc step. To check if that's the case for you as well - please enable periodic gc.

**Comment by jxtps** [comment]
Yeah, it's very strange. I have now tried: 

`Nd4j.getMemoryManager.invokeGc()` at the end of each epoch, didn't help

```scala
Nd4j.getMemoryManager.togglePeriodicGc(true)
Nd4j.getMemoryManager.setAutoGcWindow(5000)
``` 
before the loop, didn't help. 

Changing the loop to be: 
```scala
      for (i <- Range(0, epochs)) {
        val par = new ParallelWrapper.Builder(network)
          .workers(workers)
          .prefetchBuffer(workers * 2)
          .averagingFrequency(1)
          .reportScoreAfterAveraging(true)
          .build()
        par.setListeners(statsStorage)
        println(s"$name running epoch $i...")
        par.fit(iterAll)
        par.close()
        Nd4j.getWorkspaceManager.destroyAllWorkspacesForCurrentThread()
      }
```
which didn't help. 

Combining all of them: 
```scala
      Nd4j.getMemoryManager.togglePeriodicGc(true)
      Nd4j.getMemoryManager.setAutoGcWindow(5000)
      for (i <- Range(0, epochs)) {
        val par = new ParallelWrapper.Builder(network)
          .workers(workers)
          .prefetchBuffer(workers * 2)
          .averagingFrequency(1)
          .reportScoreAfterAveraging(true)
          .build()
        par.setListeners(statsStorage)
        println(s"$name running epoch $i...")
        par.fit(iterAll)
        par.close()
        Nd4j.getWorkspaceManager.destroyAllWorkspacesForCurrentThread()
        Nd4j.getMemoryManager.invokeGc()
      }
```
didn't help either. 

GPU RAM consumption just ramps: 
![image](https://user-images.githubusercontent.com/90846/61431372-22b6ee80-a8e2-11e9-9fde-459932d7ef02.png)
 you can see the "wave" of each epoch (that graph shows two separate runs). 

I have double-checked that I'm not holding on to anything externally to that loop, and as I mentioned, if I just repeat the data inside the iterator then the RAM consumption stays flat at 12G (but then I can't do checkpoint saves).

**Comment by raver119** [comment]
You shouldn't create PW in loop, create it once, and call fit as many times as you want.

Can you please create self-containing piece of java code i could run locally to reproduce this problem?

**Comment by amcelroy** [comment]
I'm having a similar issue. 

1. Create ComputationGraph model
2. Create ParallelWrapper
3. Link the model and the wrapper
4. Loop through and call .fit on the wrapper

When running without the ParallelWrapper, I get a wall of text stating that the MKL is creating layers one time. When running with the ParallelWrapper, that MKL text happens twice, and again when a new epoch is started before throwing the OOM error.

System is a dual CPU Xeon with 64GB of RAM that runs without the ParallelWrapper just fine, but after the 1st epochs throws an OOM error regardless of -Xmx flags and reducing the batch size. A single instance of the model during training uses around 20GB of RAM

**Comment by raver119** [comment]
Same question: can you create self-containing example i could use to reproduce this issue please?

**Comment by amcelroy** [comment]
Attached is a debug program that crashed and the attached error log. The zip file contains:

- Program that contains data of the size being used
- Network being used
- Pom file

[dl4j-memory-crash-dump-1563553676946_46.txt](https://github.com/eclipse/deeplearning4j/files/3411931/dl4j-memory-crash-dump-1563553676946_46.txt)

[ParallelWrapperDebug.zip](https://github.com/eclipse/deeplearning4j/files/3411936/ParallelWrapperDebug.zip)

**Comment by raver119** [comment]
Thank you very much!

**Comment by amcelroy** [comment]
Tried similar code with a dual GPU setup and got the same error. I used an AsyncDataSetIterator that wrapped the MiniBatchFileDataSetIterator to see if that was it. MiniBatchFileDataSetIterator also had a batch size of 1.

**Comment by amcelroy** [comment]
@raver119 Do you think it is related to this issue? https://github.com/eclipse/deeplearning4j/issues/3234

**Comment by raver119** [comment]
100% no.

**Comment by nimishatandon** [comment]
Is there any resolution to this ?

**Comment by treo** [comment]
This has to be retried with beta6 to see if it is even a problem anymore

**Comment by nimishatandon** [comment]
I am getting the out of memory error with beta6 and the parallelwrapper . Here is the stack trace 
![00000IMG_00000_BURST20200303221846576_COVER](https://user-images.githubusercontent.com/56741349/75850875-2af26a00-5d9d-11ea-830a-3f5b5c792693.jpg)

**Comment by raver119** [comment]
Aha, please try latest snapshot then. OOM should be fixed there.

With best regards,
raver119

**Comment by sascha08-15** [comment]
I have to report some rather awkward memory allocations. Actually my systen gets 34 million of ``AllocationPoints`` objects and is unable to clear them. GC doesn't do it nor does it a call to ``purgeCaches()`` on the ``MemoryManager``. So something is still holding on to it, right?

When I read this post, I tried to move to SNAPSHOT but that's so largely incompatible with the rest of my app (Spring Boot stack). After seeing some missing dependencies to libraries that obviously were provided, I finally gave up and reverted.

I looked at the code of ``purgeCaches()`` in 1.0.0-beta6 and SNAPSHOT whereas the latter is a no-op. Which leaves me with the question: how do I actually get rid of these objects if they are not deallocated by the workspace?

Thanks for that great DL stack and for your advice!

**Comment by raver119** [comment]
Please try with the latest snapshots. Bunch of memory-related fixes and tweaks were applied since beta6 release.

With best regards,
raver119
10 мая 2020 г., 18:04 +0300, sascha08-15 <notifications@github.com>, писал:

**Comment by sascha08-15** [comment]
One of the symptoms when moving to SNAPSHOT is, that my build pipeline broke. There's at least one test that just doesn't end.

Took a dump of the threads and I see that you've demonized the threads for ``DeallocatorService`` with a default GC window of ``100``; since I didn't configure that timeout, I wasn't really surprised it consumes a big portion of if not all CPU time; changed it to conservative 30 * 1000 ms, i.e  ``Nd4j.getMemoryManager().setAutoGcWindow(30 * 1000);`` but this test doesn't pass. Reason seems to be that it just takes way way more time to train a network.

I disabled the test and continued to investigate why the SNAPSHOT didn't nicely go together with the rest of my spring stack. Just for future generations: When you use SNAPSHOT, you have to configure ``<useBaseVersion>false</useBaseVersion>`` in the ``maven-dependency-plugin`` to preserve the timestamps of the jar files pulled out of the snapshot repo. Otherwise the MANIFEST.MF entries and the jar files don't match.

Anyways, my initial problem isn't solved as network training time seems to be poor - I'll investigate on the behavior as it took quite some time to execute that one integration test (22mins on SNAPSHOT vs. 6 mins with beta6). Anything to watch out for/to configure on the memory side? 

Thanks!

**Comment by sascha08-15** [comment]
Didn't take long
```
java.lang.RuntimeException: Op [mmul] execution failed
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1917)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6566)
	at org.nd4j.linalg.factory.Nd4j.gemm(Nd4j.java:824)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:248)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:177)
Caused by: java.lang.RuntimeException: [DEVICE] allocation failed; Error code: [2]
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2103)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1896)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6566)
	at org.nd4j.linalg.factory.Nd4j.gemm(Nd4j.java:824)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:248)
21:40:17.753 [LSTMHelpers]: MKL/CuDNN execution failed - falling back on built-in implementation
java.lang.RuntimeException: cuDNN status = 8: CUDNN_STATUS_EXECUTION_FAILED
	at org.deeplearning4j.cuda.BaseCudnnHelper.checkCudnn(BaseCudnnHelper.java:48)
	at org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.activate(CudnnLSTMHelper.java:469)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:205)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:177)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.backpropGradientHelper(LSTM.java:124)
21:40:12.994 [LSTMHelpers]: MKL/CuDNN execution failed - falling back on built-in implementation
java.lang.RuntimeException: cuDNN status = 8: CUDNN_STATUS_EXECUTION_FAILED
	at org.deeplearning4j.cuda.BaseCudnnHelper.checkCudnn(BaseCudnnHelper.java:48)
	at org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.activate(CudnnLSTMHelper.java:469)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:205)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:177)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.backpropGradientHelper(LSTM.java:124)
```
I've to note that I do integration tests with CPU whereas these exceptions have been thrown in the first 5 seconds what was supposed to be GPU-based network fitting.


Any ideas? Am I good with
```
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda-platform-redist</artifactId>
            <version>10.2-7.6-1.5.2</version>
</dependency>
```
or do I need to switch to 10.2-7.6-1.5.3?

**Comment by sascha08-15** [comment]
I've to note that I do integration tests with CPU whereas these exceptions have been thrown in the first 5 seconds what was supposed to be GPU-based network fitting.

**Comment by sascha08-15** [comment]
Sorry, my mistake - I tried out so many tweaks and still had 
```
net.getLayerWiseConfigurations().setTrainingWorkspaceMode(WorkspaceMode.NONE);
net.getLayerWiseConfigurations().setInferenceWorkspaceMode(WorkspaceMode.NONE);
```
in the code. Which then ended up raising above exception. Initial memory profile looks good. GPU usage however is down by ~20-30%. Monitoring with the script from [here](https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/gpu_monitor.sh).
My hypothesis is, this comes from the period GC. Will turn it off an see if I can improve things.

But with regards to memory, **current SNAPSHOT does fix the leaking.** Well done!

See below graphics from my heap mem alloc. 

![image](https://user-images.githubusercontent.com/26800971/81510484-3d939d00-9312-11ea-9f6b-c28fc8843e5a.png)

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
