### ISSUE TITLE
Nd4j: Can't load numpy boolean array

### ISSUE THREAD

**Issue by rnett** [eclipse/deeplearning4j#8061]
Test:
```java
@Test
public void testFromNumpy() {

    INDArray out = Nd4j.createFromNpyFile(new File("./error2.npy"));
    System.out.println(ArrayUtil.toList(ArrayUtil.toInts(out.shape())));
    System.out.println(out);
}
```

[error2.npy](https://drive.google.com/uc?export=download&id=1pQebpJV6yJy4EbMW2hnY1BIzzQ74Tpkr).  Its a boolean array, `np.array([True, True, False])`.

With the latest master, it gives something like (this was the original error, the test is with a copy of that file):
```java
Caused by: java.lang.RuntimeException: Unknown type marker
        at org.nd4j.nativeblas.Nd4jCpu$NativeOps.shapeBufferForNumpy(Native Method)
        at org.nd4j.nativeblas.BaseNativeNDArrayFactory.createFromNpyPointer(BaseNativeNDArrayFactory.java:116)
        at org.nd4j.nativeblas.BaseNativeNDArrayFactory.createFromNpyFile(BaseNativeNDArrayFactory.java:485)
        at org.nd4j.linalg.factory.Nd4j.createFromNpyFile(Nd4j.java:6920)
        at org.nd4j.imports.listeners.ImportDebugListener.opExecution(ImportDebugListener.java:48)
        ... 37 more
```

Beta4 gives a NPE that I can provide if needed.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/dl4j-test-resources/tree/master/src/main/resources/numpy_arrays/npy
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/serde/NumpyFormatTests.java#L216

Looks like we've already got decent tests for everything except boolean...

**Comment by raver119** [comment]
Added.
