### ISSUE TITLE
Error when customizing PathLabelGenerator while setting up data pipeline for semantic segmentation

### ISSUE THREAD

**Issue by linuxciscoarnaud** [eclipse/deeplearning4j#8110]
#### Issue Description
Hello guys, 
I am trying to implement semantic image segmentation with Unet network architecture, and i am having a hard time concerning how to set the data pipeline. I have managed to get the training data arranged in the following way:

- One directory in which i have the training images
- Another directory in which i put the labels (segmented images)
- I named the files in such a way that any image file in the training image directory has as corresponding label an image with same file name in the label directory.

Now i need to customize PathLabelGenerator to map the input images to their corresponding label images, and i intend to link the data by file name, meaning i want to link any training image and its corresponding label by making them have the same file name.

Here is my customized PathLabelGenerator code which i called CustomPathLabelGenerator:

```java
public class CustomPathLabelGenerator implements org.datavec.api.io.labels.PathLabelGenerator {

	public CustomPathLabelGenerator() {
		
	}
	
	NativeImageLoader imageLoader = new NativeImageLoader(512, 512, 3);
	File labelsDir = new File(System.getProperty("user.dir"), "/src/main/resources/data/trainLabels/");
	
	public Writable getLabelForPath(String path) {
		
		NDArrayWritable ndArrayWritable = null;
		try {
			Collection<File> files = FileUtils.listFiles(labelsDir, null, true);
			for(Iterator<File> iter = files.iterator(); iter.hasNext();) {
				File file = (File) iter.next();
				if(file.getName().equals(new File(path).getName())) {
					ndArrayWritable = new NDArrayWritable(imageLoader.asMatrix(new File(path).getName()));
				}
			}					
		}catch (Exception e) {
			e.printStackTrace();
		}
		
		return ndArrayWritable;
	}
	
	public Writable getLabelForPath(URI uri) {
		System.out.println("URL in first getLabelForPath function: " + new File(uri).toString());
		return getLabelForPath(new File(uri).toString());
	}
	
	public boolean inferLabelClasses() {
		return true;
	}
}
```

And here is my code for for the data pipeline:

```java
CustomPathLabelGenerator labelMaker = new CustomPathLabelGenerator();
		File mainTrainDataPath = new File(System.getProperty("user.dir"), "/src/main/resources/data/trainData/");
		FileSplit trainFileSplit = new FileSplit(mainTrainDataPath, NativeImageLoader.ALLOWED_FORMATS, rng);
		int numExamples = toIntExact(trainFileSplit.length());
		RandomPathFilter trainPathFilter = new RandomPathFilter(rng, null, numExamples);
		InputSplit[] trainInputSplit = trainFileSplit.sample(trainPathFilter);
		InputSplit trainData = trainInputSplit[0];
        DataNormalization scaler = new ImagePreProcessingScaler(0, 1);
		ImageRecordReader trainRecordReader = new ImageRecordReader(height, width, channels, labelMaker); 
		trainRecordReader.initialize(trainData);
```
But i am having the following error while just trying to check if the mapping works well:

```java
java.io.FileNotFoundException: train.tif (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:231)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:226)
	at com.neuronalstructuressegmentation.CustomPathLabelGenerator.getLabelForPath(CustomPathLabelGenerator.java:43)
	at com.neuronalstructuressegmentation.CustomPathLabelGenerator.getLabelForPath(CustomPathLabelGenerator.java:56)
	at org.datavec.image.recordreader.BaseImageRecordReader.initialize(BaseImageRecordReader.java:143)
	at com.neuronalstructuressegmentation.Segmentation.execute(Segmentation.java:90)
	at com.neuronalstructuressegmentation.Segmentation.main(Segmentation.java:380)
Exception in thread "main" java.lang.NullPointerException
	at org.datavec.image.recordreader.BaseImageRecordReader.initialize(BaseImageRecordReader.java:143)
	at com.neuronalstructuressegmentation.Segmentation.execute(Segmentation.java:90)
	at com.neuronalstructuressegmentation.Segmentation.main(Segmentation.java:380)
```

I made sure that the files are present in the respective derectories.

I currently have no idea about the origin or the cause of this error.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta3
* Platform information windows 8.1

**Comment by saudet** [comment]
Remove the call to `File.getName()`, that will take care of that.

**Comment by linuxciscoarnaud** [comment]
Thanks. I did that. Now its working fine.

**Comment by linuxciscoarnaud** [comment]
Hello,

Thanks for the help you gave me few days ago regarding this issue.
I am currently facing the following problem when running the app.

```java
Exception in thread "main" java.lang.IllegalArgumentException: Invalid input: expect NDArray with rank 4, got rank 2 with shape [4, 4]
	at org.deeplearning4j.util.ConvolutionUtils.reshape4dTo2d(ConvolutionUtils.java:443)
	at org.deeplearning4j.nn.layers.convolution.CnnLossLayer.backpropGradient(CnnLossLayer.java:79)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:148)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2621)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1369)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1329)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1149)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1098)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1065)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:999)
	at com.neuronalstructuressegmentation.Segmentation.execute(Segmentation.java:186)
	at com.neuronalstructuressegmentation.Segmentation.main(Segmentation.java:475)
```

I think this is happening during attempt to reshape the rank of the input NDArray from 4D to 2D. It turns out that the rank of my input NDArray has 2D as dimension. Could  i have declared it as 4D NDArray without any complications while customizing the PathLabelGenerator ?

Thanks for your help.

**Comment by AlexDBlack** [comment]
@linuxciscoarnaud If you are using CnnLossLayer, by definition you need 4d labels.
In DL4J, we use NCHW format for CNNs - so activations have shape [minibatch, channels, height, width]
If you are doing something like segmentation (with is generally the only thing CnnLossLayer is used for), then your labels must match that.
If you are *not* doing segmentation (and instead doing classification), then you want an OutputLayer or LossLayer instead.

**Comment by linuxciscoarnaud** [comment]
@AlexBlack
Thanks for your reply. 
I am actually doing segmentation. I used PathMultiLabelGenerator to customize generation of the labels, because i learned that it can return 4d - shape
 [1,channels,height,width]. So now the error went away. I thing my input label is now matching the NCHW format. Here is my code:

```java
public class CustomPathLabelGenerator implements PathMultiLabelGenerator {
	
	NativeImageLoader imageLoader = new NativeImageLoader(512, 512, 1);
	
	public CustomPathLabelGenerator() {}
	
	public List<Writable> getLabels(String uriPath) {
		List<Writable> ndArrayWritableList = new ArrayList<Writable>();
		File labelFile = new File(System.getProperty("user.dir"), "/src/main/resources/SplitData/Labels/" + new File(uriPath).getName());
		try {
			NDArrayWritable ndArrayWritable = new NDArrayWritable(imageLoader.asMatrix(labelFile));
			ndArrayWritableList.add(ndArrayWritable);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return ndArrayWritableList;
	}
}
```

I just want you check and tell me if i am doing it the right way.

**Comment by AlexDBlack** [comment]
That kind of looks correct, but I'm not quite following.
Are you doing multi-task segmentation?
Unless it's multi-task segmentation, you should be returning exactly *one* NDArrayWritable per getLabels call

**Comment by linuxciscoarnaud** [comment]
@alexblack
No. I am not doing Multi-task segmentation. But i wasn't able to find any other way to return one NDArrayWritable without using PathMultiLabelGenerator. So since the method in PathMultiLabelGenerator returns a list, I tought that by returning a list in which there is only ONE NDArrayWritable could work.

**Comment by linuxciscoarnaud** [comment]
@alexblack
No. I am not doing Multi-task segmentation. But i wasn't able to find any other way to return one NDArrayWritable without using PathMultiLabelGenerator. So since the method in PathMultiLabelGenerator returns a list, I tought that by returning a list in which there is only ONE NDArrayWritable per getLabels call could work.

**Comment by AlexDBlack** [comment]
Use PathLabelGenerator for that.
https://github.com/eclipse/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/io/labels/PathLabelGenerator.java#L24-L35

OK, so if you're returning only one - can you show me the shapes of the features and labels returned by the iterator? We need to narrow this down...
DataSetIterator.next() then DataSet.getLabels().shape() etc

**Comment by linuxciscoarnaud** [comment]
@alexblack
Right now just for checking i have as dataset 2 training images and 2 segmented images.

Here is the shape of the features (DataSetIterator.next()):

```java
09:31:31.733 [main] INFO  c.n.Segmentation - SHAPE THE FEATURES: ===========INPUT===================
[[[[         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
    ..., 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0]]], 


 [[[         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
    ..., 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0], 
   [         0,         0,         0  ...         0         0,         0]]]]
=================OUTPUT==================
[[[[  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
    ..., 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  242.0000,  242.0000,  242.0000  ...  242.0000  242.0000,  242.0000]]], 


 [[[  242.0000,  242.0000,  242.0000  ...  242.0000  242.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,         0  ...  255.0000  255.0000,  242.0000], 
    ..., 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 

```

Here are the labels returned:

```java
   09:34:33.973 [main] INFO  c.n.Segmentation - LABELS RETURNED BY THE ITERATOR: [[[[  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
    ..., 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  242.0000,  242.0000,  242.0000  ...  242.0000  242.0000,  242.0000]]], 


 [[[  242.0000,  242.0000,  242.0000  ...  242.0000  242.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,         0  ...  255.0000  255.0000,  242.0000], 
    ..., 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000], 
   [  255.0000,  255.0000,  255.0000  ...  255.0000  255.0000,  242.0000]]]]

```

**Comment by AlexDBlack** [comment]
ok, that looks fine (other than being unnormalized). It's probably your model configuration, post that in a gist and paste the link here - https://gist.github.com/

**Comment by linuxciscoarnaud** [comment]
@AlexDBlack 

Here is the git link:

https://gist.github.com/linuxciscoarnaud/f3e1fd35a4d864d9b0cf4991e33bf4f1

**Comment by linuxciscoarnaud** [comment]
@alexblack
It appears that only the input images are normalized, but the segmented images are not. I have tried to use ```java scaler.fitLabel(true); ``` to specify that the labels in the dataset should also be normalized. But the labels continue to appear unnormalized after execution. And right now, i don't know how to normalize them.

**Comment by linuxciscoarnaud** [comment]
@alexblack

I tried to extend ImagePreProcessingScaler as you suggested, but wasn't able to mormalize the segmented images. Here is the code:
```java
package com.neuronalstructuressegmentation;

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;

/**
 * @author Arnaud
 *
 */

public class ExtendedImagePreProcessingScaler1 extends ImagePreProcessingScaler {

	public ExtendedImagePreProcessingScaler1(double minRange, double maxRange) {
		super(minRange, maxRange);
	}
	
	@Override
    public void transformLabel(INDArray label) {
        super.transform(label);
    }
	
	@Override
    public void revertLabels(INDArray labels) {
        super.revertFeatures(labels);
    }
	
	@Override
    public void fitLabel(boolean fitLabels) {
		if (fitLabels) {
			if (isFitLabel()) {
				
			}
		}
	}
	
	@Override
    public boolean isFitLabel() {
        return true;
    }
}
```

However, i was able to normalize them by overriding only the void preProcess(DataSet toPreProcess) {} method of ImagePreProcessingScaler instead. Here is how i did:

```java
package com.neuronalstructuressegmentation;

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.api.DataSet;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;

/**
 * @author Arnaud
 *
 */

public class ExtendedImagePreProcessingScaler extends ImagePreProcessingScaler {

	public ExtendedImagePreProcessingScaler(double minRange, double maxRange) {
		super(minRange, maxRange);
	}
	
	@Override
    public void preProcess(DataSet toPreProcess) {
        INDArray features = toPreProcess.getFeatures();
        INDArray labels = toPreProcess.getLabels(); // added
        this.preProcess(features);
        this.preProcess(labels); // added
    }
}
```
In this way, both the input images and sefmented images appear normalized as folllows when i run DataSetIterator.next():

```java
12:52:32.621 [main] INFO  c.n.Segmentation - SHAPE THE FEATURES: ===========INPUT===================
[[[[    0.9490,    0.9490,    0.9490  ...    0.9490    0.9490,    0.9490], 
   [    0.7059,    0.6431,    0.5882  ...    0.6549    0.6392,    0.6196], 
   [    0.7098,    0.6627,    0.6471  ...    0.6745    0.6157,    0.6039], 
    ..., 
   [    0.6824,    0.7216,    0.7922  ...    0.3176    0.4235,    0.4706], 
   [    0.7412,    0.7725,    0.8471  ...    0.3725    0.4078,    0.4510], 
   [    0.7686,    0.8000,    0.8471  ...    0.3882    0.4078,    0.4784]]], 


 [[[    0.9490,    0.1647,    0.2118  ...    0.4157    0.4118,    0.3490], 
   [    0.9490,    0.2118,    0.2392  ...    0.4667    0.4588,    0.3725], 
   [    0.9490,    0.2471,    0.2392  ...    0.4980    0.5490,    0.4824], 
    ..., 
   [    0.9490,    0.5961,    0.6353  ...    0.2667    0.3373,    0.2667], 
   [    0.9490,    0.5922,    0.6471  ...    0.2784    0.3255,    0.2549], 
   [    0.9490,    0.6196,    0.6627  ...    0.2510    0.2980,    0.3137]]]]
=================OUTPUT==================
[[[[    0.9490,    0.9490,    0.9490  ...    0.9490    0.9490,    0.9490], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
    ..., 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000]]], 


 [[[    0.9490,    0.9490,    0.9490  ...    0.9490    0.9490,    0.9490], 
   [         0,         0,         0  ...    1.0000    1.0000,    1.0000], 
   [         0,         0,         0  ...    1.0000    1.0000,    1.0000], 
    ..., 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000  ...    1.0000    1.0000,    1.0000]]]]
```
I still continue to ask myself why it did not work with the process you suggested.

**Comment by linuxciscoarnaud** [comment]
@alexblack

I was able to work out the rank 2 CnnLossLayer issue. You are right, there is nothing wrong with the configuration. I was making a huge mistake when customizing path Label Generator. When implementing the PathLabelGenerator interface, i forgot to make sure that the boolean inferLabelClasses() method returns false. So it was actually returning true, which resulted in generating a 2D NDArray (rank 2 and with shape [x,y]), which is inconsistent with the expected 4D NDArray used for CnnLossLayer.

Here is the code:

```java
package com.neuronalstructuressegmentation;

import java.io.File;
import java.net.URI;

import org.datavec.api.io.labels.PathLabelGenerator;
import org.datavec.api.writable.NDArrayWritable;
import org.datavec.api.writable.Writable;
import org.datavec.image.loader.NativeImageLoader;

/**
 * @author Arnaud
 *
 */

public class CustomPathLabelGenerator implements PathLabelGenerator {

	NativeImageLoader imageLoader = new NativeImageLoader(512, 512, 1);
	Writable ndArrayWritable = null;
	
	public CustomPathLabelGenerator() {}
	
	public Writable getLabelForPath(String path) {		
		
		File labelFile = new File(System.getProperty("user.dir"), "/src/main/resources/SplitData/Labels/" + new File(path).getName());
		try {
			ndArrayWritable = new NDArrayWritable(imageLoader.asMatrix(labelFile));
		} catch(Exception e) {
			e.printStackTrace();
		}
		
		return ndArrayWritable;
	}
	
	public Writable getLabelForPath(URI uri) {
		return getLabelForPath(new File(uri).toString());
	}
	
	public boolean inferLabelClasses() {
		return true;
	}
}
```

**Comment by linuxciscoarnaud** [comment]
@alexblack

I was able to work out the rank 2 CnnLossLayer issue. You are right, there is nothing wrong with the configuration. I was making a huge mistake when customizing path Label Generator. When implementing the PathLabelGenerator interface, i forgot to make sure that the boolean inferLabelClasses() method return false. So it was actually returning true, which resulted in generating a 2D NDArray (rank 2 and with shape [x,y]), which is inconsistent with the expected 4D NDArray used for CnnLossLayer.

Here is the code:

```java
package com.neuronalstructuressegmentation;

import java.io.File;
import java.net.URI;

import org.datavec.api.io.labels.PathLabelGenerator;
import org.datavec.api.writable.NDArrayWritable;
import org.datavec.api.writable.Writable;
import org.datavec.image.loader.NativeImageLoader;

/**
 * @author Arnaud
 *
 */

public class CustomPathLabelGenerator implements PathLabelGenerator {

	NativeImageLoader imageLoader = new NativeImageLoader(512, 512, 1);
	Writable ndArrayWritable = null;
	
	public CustomPathLabelGenerator() {}
	
	public Writable getLabelForPath(String path) {		
		
		File labelFile = new File(System.getProperty("user.dir"), "/src/main/resources/SplitData/Labels/" + new File(path).getName());
		try {
			ndArrayWritable = new NDArrayWritable(imageLoader.asMatrix(labelFile));
		} catch(Exception e) {
			e.printStackTrace();
		}
		
		return ndArrayWritable;
	}
	
	public Writable getLabelForPath(URI uri) {
		return getLabelForPath(new File(uri).toString());
	}
	
	public boolean inferLabelClasses() {
		return false;
	}
}
```

**Comment by linuxciscoarnaud** [comment]
@alexblack

I was able to work out the rank 2 CnnLossLayer issue. You are right, there is nothing wrong with the configuration. I was making a huge mistake when customizing path Label Generator. When implementing the PathLabelGenerator interface, i forgot to make sure that the boolean inferLabelClasses() method returns false. So it was actually returning true, which resulted in generating a 2D NDArray (rank 2 and with shape [x,y]), which is inconsistent with the expected 4D NDArray used in CnnLossLayer.

Here is the code:

```java
package com.neuronalstructuressegmentation;

import java.io.File;
import java.net.URI;

import org.datavec.api.io.labels.PathLabelGenerator;
import org.datavec.api.writable.NDArrayWritable;
import org.datavec.api.writable.Writable;
import org.datavec.image.loader.NativeImageLoader;

/**
 * @author Arnaud
 *
 */

public class CustomPathLabelGenerator implements PathLabelGenerator {

	NativeImageLoader imageLoader = new NativeImageLoader(512, 512, 1);
	Writable ndArrayWritable = null;
	
	public CustomPathLabelGenerator() {}
	
	public Writable getLabelForPath(String path) {		
		
		File labelFile = new File(System.getProperty("user.dir"), "/src/main/resources/SplitData/Labels/" + new File(path).getName());
		try {
			ndArrayWritable = new NDArrayWritable(imageLoader.asMatrix(labelFile));
		} catch(Exception e) {
			e.printStackTrace();
		}
		
		return ndArrayWritable;
	}
	
	public Writable getLabelForPath(URI uri) {
		return getLabelForPath(new File(uri).toString());
	}
	
	public boolean inferLabelClasses() {
		return false;
	}
}
```

**Comment by alexblack** [comment]
@linuxciscoarnaud I'm not the person you're talking to, I'd appreciate not being continually mentioned here, thanks
