### ISSUE TITLE
UIServer.getInstance() throws IllegalArgumentException under JDK 1.8.0_51+

### ISSUE THREAD

**Issue by cowwoc** [eclipse/deeplearning4j#8112]
#### Issue Description

`UIServer server = UIServer.getInstance();` throws an exception under 1.8.0_51+ (in my case, I am using JDK 13)

```
Exception in thread "main" java.lang.IllegalArgumentException: Don't know how to bind argument of type class net.jodah.typetools.TypeResolver$Unknown
	at play.routing.RoutingDsl.pathBindableFor(RoutingDsl.java:233)
	at play.routing.RoutingDsl.with(RoutingDsl.java:190)
	at play.routing.RoutingDsl.access$000(RoutingDsl.java:66)
	at play.routing.RoutingDsl$PathPatternMatcher.build(RoutingDsl.java:362)
	at play.routing.RoutingDsl$PathPatternMatcher.routeTo(RoutingDsl.java:298)
	at org.deeplearning4j.ui.play.PlayUIServer.runMain(PlayUIServer.java:179)
```

Per https://github.com/playframework/playframework/issues/5136 this is a known bug. Upgrading the Play dependency (which is extremely out of date anyway) will fix this problem.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): Windows 10.0.18362.295

**Comment by AlexDBlack** [comment]
Thanks for the issue, but I'll close this: upgrading the Play version has already been done in the following PR and should be merged soon.
https://github.com/eclipse/deeplearning4j/pull/8098
