### ISSUE TITLE
CnnSentenceDataSetIterator.loadSingleSentence() throws ND4JIllegalStateException if word vectors missing word

### ISSUE THREAD

**Issue by cowwoc** [eclipse/deeplearning4j#8120]
#### Issue Description

If a user invokes:

```
INDArray featuresFirstNegative = ((CnnSentenceDataSetIterator) testData).loadSingleSentence("McDonald's coffee");
```

where the underlying word vectors do not contain one of the words in the sentence then the following exception is thrown:

```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [1, 1, 0, 300] contains dimension size values < 1 (all dimensions must be 1 or more)
    at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:4675)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4611)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4114)
    at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.loadSingleSentence(CnnSentenceDataSetIterator.java:161)
```

Expected behavior: Clearer error message explaining that the word vectors did not contain the requested word, and specify exactly which word was missing.

This issue might be a duplicate of https://github.com/eclipse/deeplearning4j/issues/3254 but it looks like it was never fixed correctly.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* Platform information (OS, etc): Windows 10.0.18362.295
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by AlexDBlack** [comment]
Thanks for reporting - fixed here, will be merged to eclipse/deeplearning4j master soon.
https://github.com/SkymindIO/deeplearning4j/pull/141
