### ISSUE TITLE
NullPointerException if UnknownWordHandling.UseUnknownVector

### ISSUE THREAD

**Issue by cowwoc** [eclipse/deeplearning4j#8121]
#### Issue Description

If a user configured `CnnSentenceDataSetIterator` with `unknownWordHandling(UnknownWordHandling.UseUnknownVector)` and the code runs across an unknown word then the following exception will be thrown:

```
Exception in thread "AMDSI prefetch thread" java.lang.RuntimeException: java.lang.NullPointerException
    at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:396)
Caused by: java.lang.NullPointerException
    at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1398)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:2378)
    at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:375)
    at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:261)
    at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:62)
    at org.deeplearning4j.datasets.iterator.impl.MultiDataSetIteratorAdapter.next(MultiDataSetIteratorAdapter.java:78)
    at org.deeplearning4j.datasets.iterator.impl.MultiDataSetIteratorAdapter.next(MultiDataSetIteratorAdapter.java:29)
    at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:368)
```

There are actually two bugs at play here:

1. `BaseNDArray.java:1398` invokes:

```
        Preconditions.checkState((this.isScalar() && arr.isScalar()) || (this.isVector() && arr.isVector()) || Shape.shapeEqualWithSqueeze(this.shape(), arr.shape()),
                "Cannot assign arrays: arrays must both be scalars, both vectors, or shapes must be equal other than size 1 dimensions. Attempting to do x.assign(y)" +
                        " with x.shape=%ndShape and y.shape=%ndShape", this, arr );
```

but if `arr` is `null` then the aforementioned `NullPointerException` is thrown. Please handle the possibility of `arr` being `null`.

2. CnnSentenceDataSetIterator:186 invokes:

```
        if (unknownWordHandling == UnknownWordHandling.UseUnknownVector && word == UNKNOWN_WORD_SENTINEL) { //Yes, this *should* be using == for the sentinel String here
            vector = unknown;
        }
```

but the field `unknown` is never set, so its value is `null`. This means that if an unknown word is encountered, `getVector()` returns `null` and the aforementioned exception is thrown.

Expected behavior: You should probably return something other than `null`.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta 4
* Platform information (OS, etc):  Windows 10.0.18362.295
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by AlexDBlack** [comment]
Thanks for reporting - fixed here, will be merged to eclipse/deeplearning4j master soon.
https://github.com/SkymindIO/deeplearning4j/pull/141
