### ISSUE TITLE
failure to import Keras model

### ISSUE THREAD

**Issue by jamesd8** [eclipse/deeplearning4j#8125]
When calling KerasModelImport.importKerasModelAndWeights, I get the following exception for a Keras ResNet152 model:

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Scale. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:172)
	at noplay.tsne.Tsne$.testResnet152(Tsne.scala:58)
	at noplay.tsne.Tsne$.main(Tsne.scala:291)
	at noplay.tsne.Tsne.main(Tsne.scala)
```

The Keras model came originally from:

https://gist.github.com/flyyufelix/7e2eafb149f72f4d38dd661882c554a6

I loaded it up in Keras and saved it with the model structure and then tried to load it into DL4J.

#### Version Information

* Deeplearning4j version: 1.0.0-beta4
* Windows 10 64 bit
* CUDA 10, but shouldn't matter

#### Additional Information

I tried attaching the model file, but it won't attach because it is far too big. Let me know if there is another way to get it to you.

**Comment by jamesd8** [comment]
I'd also be fine with an expanded Model Zoo with more DL4J-based models. A Resnet 101 and 152 trained on ImageNet would be helpful, for example.

**Comment by agibsonccc** [comment]
Guessing this is a custom Layer within the keras model zoo. We need to support Model yet (embedded layers) as well as make registering nested layers a bit more robust. More docs here: https://deeplearning4j.konduit.ai/keras-import/overview

Closing this due to inactivity.
