### ISSUE TITLE
Keras H5-Model import throws UnsupportedKerasConfigurationException

### ISSUE THREAD

**Issue by markusbartel1** [eclipse/deeplearning4j#8140]
#### Issue Description

An model is created and trained with Keras. Model is exported and re-imported in DL4J.
An exception is raised, stating that an 5D-Input is not allowed. Model implements a tiny Yolo2 algorithm (see file [TinyYoloV2.txt](https://github.com/eclipse/deeplearning4j/files/3534677/TinyYoloV2.txt)).
Importing the model back to Keras was successful.

#### Version Information

* Deeplearning4j version -> 1.0.0-beta4
* Platform information (OS, etc) -> Windows 10
* CUDA version, if used -> 10.0

#### Additional Information

15:18:39.926 [main] FATAL de.zeiss.deeplearning.Yolo2Test - Inputs with 5 dimensions not supported. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Inputs with 5 dimensions not supported. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasInput.<init>(KerasInput.java:69) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:263) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:172) ~[deeplearning4j-modelimport-1.0.0-beta4.jar:?]
	at de.zeiss.deeplearning.net.NeuralNetManager.kerasModel(NeuralNetManager.java:122) ~[classes/:?]
	at de.zeiss.deeplearning.Yolo2Test.testSurgicalInstrumentRedColorWithKerasModel(Yolo2Test.java:170) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRu
nnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]

see Pom's attached -> [Poms.zip] https://github.com/eclipse/deeplearning4j/files/3534704/Poms.zip)

#### Contributing

**H5-ModelFile can not be attached. If file is needed, please contact me for a large-file-transfer.**

**Comment by agibsonccc** [comment]
We've fixed quite a tew issues since this. Closing due to inactivity.
