### ISSUE TITLE
ND4J backend not found, but cuda installed.

### ISSUE THREAD

**Issue by nsoft** [eclipse/deeplearning4j#8153]
#### Issue Description

I'm unable to run DL4J with nvidia CUDA back end despiite following the instructions here:
https://deeplearning4j.org/docs/latest/deeplearning4j-config-gpu-cpu
Project works fine with native back end. When I debug, I can see the service loader finding the JCublasBackend.java class and then failing on isAvailable().

As far as I can tell I've done everything recommended by the linked page, which certainly seems to represent itself as "all you need to do to use CUDA"... If I had to guess, this will likely boil down to needing to say something more specific than "If you have CUDA v9.2+ installed" because clearly from the output of nvidia-smi it's installed, and clearly I have the dep on the classpath but you aren't able to find it... So probably you've made some  assumption regarding how it was installed.

#### Version Information

* Deeplearning4j version 
```
    // DL4J dependencies: https://deeplearning4j.org/docs/latest/deeplearning4j-config-buildtools
    compile "org.deeplearning4j:deeplearning4j-core:1.0.0-beta4"
   //    compile "org.nd4j:nd4j-native-platform:1.0.0-beta4"
    compile 'org.nd4j:nd4j-cuda-10.1:1.0.0-beta4'
```
* Platform information (OS, etc) 
Ubuntu 18.04 LTS
```
gus@ns-l1:~$ uname -a
Linux ns-l1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* CUDA version, if used
installed via instructions on this page: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork
```
gus@ns-l1:~$ nvidia-smi 
Mon Aug 26 10:59:52 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:42:00.0  On |                  N/A |
| 33%   32C    P8    18W / 250W |    689MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2149      G   /usr/lib/xorg/Xorg                            24MiB |
|    0      2624      G   /usr/bin/gnome-shell                          50MiB |
|    0      3929      G   /usr/lib/xorg/Xorg                           283MiB |
|    0      4090      G   /usr/bin/gnome-shell                         207MiB |
|    0      4385      G   share/jetbrains-toolbox/jetbrains-toolbox      3MiB |
|    0      4789      G   .../IDEA-U/ch-0/191.7479.19/jre64/bin/java     3MiB |
|    0      6264      G   /usr/lib/firefox/firefox                       2MiB |
|    0      6283      G   /usr/lib/firefox/firefox                       2MiB |
|    0      6304      G   /usr/lib/firefox/firefox                       2MiB |
|    0      6890      G   ...quest-channel-token=6230709894619332622    36MiB |
|    0      7781      G   /usr/lib/firefox/firefox                       2MiB |
|    0      8798      G   ...quest-channel-token=9262909411802725788    65MiB |
+-----------------------------------------------------------------------------+

```
* NVIDIA driver version, if in use
(see above)

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
Putting log here cause it's short... produced within intellij, but an exec task in ./gradlew produces identical results (wrapped in gradle build kruft of course).
```
11:04:40.951 [main] WARN  org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: no jnicudart in java.library.path
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:671)
	at com.CUSTOMER_REDACTED.dl4j.CLASSNAME_REDACTED.main(CLASSNAME_REDACTED.java:93)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5768)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
	... 2 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:213)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5765)
	... 3 more
```
* pom.xml file or similar (also in a Gist)

#### Contributing

Sure if needed... once you help find the fix :)

**Comment by raver119** [comment]
Try to use `nd4j-cuda-10.1-platform` dependency

**Comment by raver119** [comment]
Good point, thanks. We'll fix that.
