### ISSUE TITLE
ND4J CUDA: LapackTest.testCholeskyL/U failing

### ISSUE THREAD

**Issue by AlexDBlack** [eclipse/deeplearning4j#8167]
Fine on CPU.

Windows 10, CUDA 10.1 update 1, GTX 970, latest master.

```
org.nd4j.linalg.api.blas.BlasException: cusolverDnDpotrf_bufferSize failed: 3

	at org.nd4j.linalg.jcublas.blas.JcublasLapack.dpotrf(JcublasLapack.java:551)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.potrf(BaseLapack.java:102)
	at org.nd4j.linalg.api.blas.LapackTest.testCholeskyL(LapackTest.java:83)
```

**Comment by saudet** [comment]
@rcorbish Would you know by any chance the fix?

**Comment by rcorbish** [comment]
Let me take a look

**Comment by AlexDBlack** [comment]
Confirmed passing now, thanks.
