### ISSUE TITLE
org.nd4j.linalg.exception.ND4JIllegalStateException: Can't establish connection afet 10 seconds. Terminating...

### ISSUE THREAD

**Issue by gharick** [eclipse/deeplearning4j#8183]
#### Issue Description

I got : WARN scheduler.TaskSetManager: Lost task 0.0 in stage 5.0 (TID 34, hadoop-Lenovo-G50-70, executor 1): org.nd4j.linalg.exception.ND4JIllegalStateException: Can't establish connection afet 10 seconds. Terminating...
at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.addConnection(AeronUdpTransport.java:314)
	at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.launch(AeronUdpTransport.java:344)
	at org.nd4j.parameterserver.distributed.v2.ModelParameterServer.launch(ModelParameterServer.java:380)
	at org.deeplearning4j.spark.parameterserver.pw.SharedTrainingWrapper.run(SharedTrainingWrapper.java:365)
	at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPathsAdapter.call(SharedFlatMapPaths.java:94)
	at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPathsAdapter.call(SharedFlatMapPaths.java:62)
	at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:40)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

when trying to fit a network in spark cluster with 2 nodes and a master.
knowing that I can see both nodes in Yarn webUI and I can ssh both
the application keeps going logging :
2019-08-31 20:05:52,204 INFO storage.BlockManagerInfo: Removed broadcast_10_piece0 on hadoop-Aspire-E5-573:33563 in memory (size: 21.8 KB, free: 93.1 MB)
2019-08-31 20:05:52,327 INFO storage.BlockManagerInfo: Removed broadcast_10_piece0 on hadoop-Lenovo-G50-70:39859 in memory (size: 21.8 KB, free: 83.6 MB)
2019-08-31 20:05:52,369 INFO spark.ContextCleaner: Cleaned accumulator 29
2019-08-31 20:05:52,369 INFO spark.ContextCleaner: Cleaned accumulator 96
2019-08-31 20:05:52,369 INFO spark.ContextCleaner: Cleaned accumulator 97
2019-08-31 20:05:52,369 INFO spark.ContextCleaner: Cleaned accumulator 92
again and again with different accumulator numbers and different broadcast number
then gets stuck at one of them

**Comment by RobAltena** [comment]
That is a networking issue on your side: " Can't establish connection".

**Comment by gharick** [comment]
Not sure where the problem is, 
as I mentioned, I can see some tasks running in both nodes before I get this error. Also, RDD files writing in HDFS works fine with no errors with 2 containers 1 in each node, exporting doese also work successfully, but I get this error when I try to fit my network

**Comment by AlexDBlack** [comment]
Right, the most likely explanation here is your firewall or network configuration - ports that are not open/accessible are being used for training.

Have a look at the ports configuration here (unicastPort etc - it's configurable).
https://deeplearning4j.org/docs/latest/deeplearning4j-scaleout-parameter-server

If you are sure that you network is correctly set up for those ports, and your training job is correctly configured, post your configuration and we'll take a look.
