### ISSUE TITLE
java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.lengthLong()J

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8206]
INDArray.equals() throws exception:
java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.lengthLong()J
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:539)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equalsWithEps(BaseNDArray.java:4491)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equals(BaseNDArray.java:4547)
	at org.nd4j.linalg.jcublas.JCublasNDArray.equals(JCublasNDArray.java:507)
	at com.cq.deepGa4j.operator.CrossOverOperator.cross(CrossOverOperator.java:109)
	at com.cq.deepGa4j.operator.CrossOverOperatorTest.testCrossOver(CrossOverOperatorTest.java:69)

#### Version Information

* Deeplearning4j 1.0.0-SNAPSHOT
* Platform information : win10
* CUDA version,10.0

**Comment by AlexDBlack** [comment]
Refresh your snapshots. You likely have some modules that are older than others or otherwise outdated.
The lengthLong method was removed entirely recently.
