### ISSUE TITLE
jnicudart.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by lightway82** [eclipse/deeplearning4j#8221]
Nd4j  does't use cuda, but switches to cpu.
I use org.bytedeco cuda dependency.

```
       INDArray zeros = Nd4j.zeros(3, 5);
        System.out.println(zeros);

        INDArray indArray = Nd4j.create(new float[]{1, 2, 3, 4}, new int[]{2, 2});
        System.out.println(indArray);

 WARN org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: C:\Users\Anama\.javacpp\cache\cuda-10.1-7.6-1.5.1-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jnicudart.dll: Can't find dependent libraries
13:57:47.063 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
13:57:47.948 [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for OpenMP: 4
13:57:48.793 [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 4
13:57:48.803 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
13:57:48.803 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [2,0GB];
13:57:48.803 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [MKL] 
[[         0,         0,         0,         0,         0], 
 [         0,         0,         0,         0,         0], 
 [         0,         0,         0,         0,         0]]
[[    1.0000,    2.0000], 
 [    3.0000,    4.0000]]
```

Dependencies:

  implementation("org.bytedeco","cuda-platform", "10.1-7.6-1.5.1")
  implementation("org.nd4j","nd4j-native-platform", "1.0.0-beta5")
  implementation("org.nd4j","nd4j-cuda-10.1-platform", "1.0.0-beta5")

What i do wrong?

**Comment by raver119** [comment]
Show `nvcc --version` output please

**Comment by lightway82** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by lightway82** [comment]
I installed latest cuda version:

```
14:49:25.424 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:130)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:56)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:49)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:37)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:68)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:34)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5216)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5153)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:182)
	at life.biomedis.noise.nn_train.Main.main(Main.java:8)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:106)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:34)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path: [H:\Programms\Java\jdk-12.0.1\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, ., C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Users\Anama\AppData\Local\Programs\Git\bin, H:\Programms\Java\jdk-12.0.1\bin, C:\Program Files\MySQL\MySQL Shell 8.0\bin\, C:\Program Files\PowerShell\6\, H:\Programms\Anaconda3, H:\Programms\Scala\bin, H:\Programms\hadoop-3.1.2\bin, H:\Programms\spark-2.4.3-bin-hadoop2.7\bin, H:\Programms\apache-maven-3.6.1\\bin, D:\Program Files\nodejs\, H:\Programms\Java\apache-maven-3.6.1\bin, C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\, C:\Users\Anama\AppData\Local\Microsoft\WindowsApps, C:\Users\Anama\AppData\Local\Programs\Git\cmd, C:\Program Files\MySQL\MySQL Server 8.0\bin, C:\Users\Anama\AppData\Roaming\npm, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
	at java.base/java.lang.System.loadLibrary(System.java:1902)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1487)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1040)
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:84)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Anama\.javacpp\cache\nd4j-cuda-10.1-1.0.0-beta5-windows-x86_64.jar\org\nd4j\nativeblas\windows-x86_64\jnind4jcuda.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1461)
	... 19 more

```

**Comment by saudet** [comment]
The DLLs for CUDA are probably missing from the PATH. Make this isn't the case:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows
