### ISSUE TITLE
about Workspace in multiGPU mode

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#8231]
#### Issue Description

My code:
```
public void init() {
        selectOperator = new TournamentSelectOperator();
        crossOverOperator = new CrossOverOperator();
        crossOverOperator.setIndivalFactory(indivalFactory);
        mutateOperator = new MutateOperator();
        //create config with 512MB memory space pre allocated
        wcConfig = WorkspaceConfiguration.builder()
                .initialSize(512L * 1024L * 1024L)
                .policyLearning(LearningPolicy.OVER_TIME)
                .build();        
    }
 public void initPop() {
        int popSize = evolveParams[0].getPopSize();
        currIndivs = new ArrayList<>(popSize);

        for (int i = 0; i < popSize; ++i) {
            AbstractIndividual indiv = indivalFactory.getInstance();
            indiv.initChromosome();
            currIndivs.add(indiv);
        }
      
        computeFitness(currIndivs, 0);
    }
 private void evolve(int genIndex) {
        try (MemoryWorkspace wsEvolve = Nd4j.getWorkspaceManager().getAndActivateWorkspace(wcConfig, "evolve")) {
        ... ...
        }
}
 public void evolve() {
        try (MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(wcConfig, "initPop")) {
            initPop();
            for (int i = 0; i < this.maxEvoluteGenerationCount; ++i) {
                evolve(i);
            }
        }
    }
```
There are 6 Gpus, each  corresponds to a thread. So, there are 6 Workspaces. 

Exceptions thrown:
Exception in thread "pool-1-thread-5" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-3" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-2" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-4" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-6" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-1" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [initPop]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1202)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3137)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3118)
	at com.cq.deepGaTrader4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:149)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTradeWithMultiLayerNet(NeuroTradeIndiv.java:84)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.simulateTrade(NeuroTradeIndiv.java:78)
	at com.cq.deepGaTrader4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:52)
	at com.cq.deepGa4j.Population.computeFitness(Population.java:356)
	at com.cq.deepGa4j.Population.initPop(Population.java:209)
	at com.cq.deepGa4j.Population.evolve(Population.java:215)
	at com.cq.deepGa4j.operator.PopulationEvolver.run(PopulationEvolver.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
#### Version Information
Deeplearning4j 1.0.0-beta5
Platform information ubuntu 18.4
CUDA version, nd4j-cuda-10.0-platform

**Comment by raver119** [comment]
This isn't about multi-gpu. It just says that you shouldn't wrap your NN into workspace. Everything that happens within NN is already wrapped by workspace

**Comment by cqiaoYc** [comment]
How to not wrap my NN into workspace? using "try(MemoryWorkspace ws = Nd4j.getWorkspaceManager().scopeOutOfWorkspaces()) "? Or set setInferenceWorkspaceMode(WorkspaceMode.NONE)?

**Comment by raver119** [comment]
scopeOutOfWorkspaces

**Comment by raver119** [comment]
or, better, structure your app internally in a way that avoid being within workspace
